### ISSUE TITLE
Entry does not get added to Mongo, virustotal has no attribute 'has_key'

### ISSUE THREAD

**Issue by pashashocky** [spender-sandbox/cuckoo-modified#105]
It seems that virus total is not responding to the request and the list is not being formed correctly on some analyses, it causes the reporting module to fail. The status becomes 'reported' although when opening the analysis an is error presented: 'Analysis does not exist'. 

After re-running the processing on that analysis, it seems to work fine. 

Thank you

```
2016-04-28 13:23:31,604 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/var/cuckoo-live/utils/../lib/cuckoo/core/plugins.py", line 632, in process
    current.run(self.results)
  File "/var/cuckoo-live/utils/../modules/reporting/mongodb.py", line 158, in run
    if results.has_key("virustotal") and results["virustotal"] and results["virustotal"].has_key("positives") and results["virustotal"].has_key("total"):
AttributeError: 'list' object has no attribute 'has_key'
```

**Comment by spender-sandbox** [comment]
Yes, I fixed that early this morning, it was a problem on VirusTotal's end, as they send data back completely against what's documented in their API.

-Brad
