### ISSUE TITLE
maldocs refusing to give up iocs.

### ISSUE THREAD

**Issue by mallorybobalice** [spender-sandbox/cuckoo-modified#107]
hi, 

previous waves from the same campaign downloaded exes fine 

however, the ones on the 28/29th 
f2ac1460c18a7e400b38c8d15e00104a
55cab57c309294edc2e262a8af252008
1eea65b449bb78b166b83133d6467f2a

refuse to make network connections and aside from sandbox reporting sleeping (but getting around it), doesn't make http requests for EXEs anymore. (although it seems ok in malwr but not always on HA) 
Was wondering if someone has encountered a similar issue/has any workarounds. 

guess i'll go run pafish to see what might be leaking. 

mb

**Comment by mallorybobalice** [comment]
ok, not good. after running pafish. 

looks like esx vms without vmware tools by default leak a lot of CPU, disk and the like info
rdtsc aside (I believe there's already a thread) - any suggestions? 

I'm thinking: 
a) bit more ram instead of 1gb
b) change macs to vmware unrelated
c) maybe install the rdtsc driver (i'm not sure that sounded safe) 

not sure what I can do for:
[pafish] CPU VM traced by checking hypervisor bit in cpuid feature bits
[pafish] CPU VM traced by checking cpuid hypervisor vendor for known VM vendors
[pafish] VMware serial number traced using WMI

```
[pafish] Start
[pafish] Windows version: 6.1 build 7601
[pafish] CPU: GenuineIntel (HV: VMwareVMware)        Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
[pafish] CPU VM traced by checking the difference between CPU timestamp counters (rdtsc) forcing VM exit
[pafish] CPU VM traced by checking hypervisor bit in cpuid feature bits
[pafish] CPU VM traced by checking cpuid hypervisor vendor for known VM vendors
[pafish] Sandbox traced by checking if pysical memory is less than 1Gb
[pafish] VMware traced using MAC address starting with 00:05:69, 00:0C:29, 00:1C:14 or 00:50:56
[pafish] VMware serial number traced using WMI
[pafish] End
```

**Comment by mallorybobalice** [comment]
also, any easy way to track the specific wmi queries from the analysis logs?

**Comment by jbremer** [comment]
You're correct - at least the second sample (55cab57c309294edc2e262a8af252008) is actively looking for information obtained from the `Win32_ComputerSystem` WMI query. In particular it checks `Manufacturer` and `Model`. Changing their values from something-virtualbox to anything else makes the analysis go through and download the actual payload, see also the following screenshot.

http://cuckoo.sh/dce3d0afb310a749/screenshot.png

This is new functionality I'm currently working on and is not yet pushed upstream in its entirety (in the main Cuckoo branch, naturally).

**Comment by spender-sandbox** [comment]
You heard it here folks, just use the upstream Cuckoo and this particular malware* will run.  Closing this.

*Experience may vary against the majority of other in-the-wild malware.

**Comment by mallorybobalice** [comment]
>In particular it checks Manufacturer and Model. Changing their values from something-virtualbox to anything else makes the analysis go through and download the actual payload, see also the following screenshot.


yep did notice WmiPrvSe.exe running as well. Thanks for the tip on what it was querying. I'll have a look if I can edit those out in the registry for now. any chance of a short term hints set on modifying the guest for now until upstream changes and Brad possibly porting them here? I realize there's a few dozen things people can query (and it's surprising to see common maldocs to only now seemingly start to use it) - whether it's loaded drivers for the guest, computer model info (system , disk, etc) , bios info etc... but are there plans to systematically address and fake those or does Brad's comment mean 'out of scope/build some physical PCs if worried'?  (http://docs.cuckoosandbox.org/en/latest/installation/guest_physical/saving/ errr... we'll get started on it I suppose, but it's by no means a quick fix :( ) 

>You heard it here folks, just use the upstream Cuckoo and this particular malware* will run.

butbutbut I can't quite tell if JB meant already in upstream or 'eventually sort of will' ? 

also any extra comments on addressing the CPU ID related ones? 
```
[pafish] CPU: GenuineIntel (HV: VMwareVMware)        Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
[pafish] CPU VM traced by checking the difference between CPU timestamp counters (rdtsc) forcing VM exit
[pafish] CPU VM traced by checking hypervisor bit in cpuid feature bits
[pafish] CPU VM traced by checking cpuid hypervisor vendor for known VM vendors
```
