### ISSUE TITLE
problem with latest cuckoomon DLL

### ISSUE THREAD

**Issue by MerX1030** [spender-sandbox/cuckoo-modified#11]
latest cuckoomon DLL, somehow, failed to hook APIs on previously samples.
Hooks fine using cuckoomon DLL from previous commit:
https://github.com/spender-sandbox/cuckoo-modified/commit/b713be0c27535851d6d757f47d2e7926c2999574#diff-d5a3b633e57a670a51110586b006ba72

You may try the following samples for reference:
MD5	2444348a2db8061607e9e20ae95b003d
SHA1	05821f79ada8104be9ec2c01bdbbe7d120c6f94b
SHA256	bc2c2036664aa1954a039cbce4da4a66e492c648408ceb784acda70df43d95ef
SHA512	6a9061bcae88af68cfb6b5c578b854af903cabf2593a2c4b846b71610e29184415cc9c3b5e40fbc7733c93fe984219478ad537d36be938dc8e4067ef9235f6cc

**Comment by KillerInstinct** [comment]
This sample runs fine with Win7x86 latest commit in my rig.

**Comment by MerX1030** [comment]
confirmed that the issue was due to an application I installed on the guest OS that also hooks certain APIs. Closing this case.
Thanks!
