### ISSUE TITLE
Unable to import plugin "modules.reporting.retention"

### ISSUE THREAD

**Issue by adiluca89** [spender-sandbox/cuckoo-modified#116]
After installing spender-sandbox/cuckoo-modified on Ubuntu 14.04.3 LTS, when trying to start cuckoo.py I receive the following error:

2016-05-05 13:42:02,036 [root] DEBUG: Importing modules...
2016-05-05 13:42:03,694 [root] CRITICAL: CuckooCriticalError: Unable to import plugin "modules.reporting.retention": cannot import name _UNPACK_INT

I have searched everywhere for a possible solution, but with no success. In my previous installation with Cuckoo + VirtualBox everything was fine, but in this installation with Cuckoo + KVM I get the above mentioned error.

Could anyone please help me to fix this?

**Comment by KillerInstinct** [comment]
Can you try this please?

```
sudo pip uninstall bson
sudo pip uninstall pymongo
sudo pip install pymongo
```

**Comment by adiluca89** [comment]
It worked. Thank you very much!
