### ISSUE TITLE
RateLimit ImportError

### ISSUE THREAD

**Issue by kevthehermit** [spender-sandbox/cuckoo-modified#117]
This an issue with ratelimit and i have raised it upstream. https://github.com/jsocol/django-ratelimit/issues/105  Also raising here for awareness.

Django 1.9 No longer supports django.utils.importlib import_module

**Comment by doomedraven** [comment]
easy solution 

try:
    # Django versions >= 1.9
    from django.utils.module_loading import import_module
except ImportError:
    # Django versions < 1.9
    from django.utils.importlib import import_module
'

**Comment by kevthehermit** [comment]
Its fixed upstream pip install --upgrade django-ratelimit wasnt updating properly maybe because its pulled from the git not pypi. reinstalling requirements.txt and forcing upgrade fixed it
