### ISSUE TITLE
Stucks on Processing 

### ISSUE THREAD

**Issue by marek2003** [spender-sandbox/cuckoo-modified#119]
Hi all,
Cuckoo has been working without any issues except today when I came across to  one JS. The analysis seems completed but it stucks on processing. I tried to  :Disable automated interaction and  No Injection (disable behavioral analysis) with no luck.
The worse thing is that every file I try to upload after that file they go to "pending" even if I 've several free VM's.
the Js is zipped and can be downloaded here: https://malwr.com/analysis/NDNiYjgzMjc2NmZjNGJjZThmYTZhNTM4NGIyZTAxZjk/ 
thanks for help
Marco

**Comment by marek2003** [comment]
I decided to wait and finally i got the report but here is the output of processing stings:
Processing ( 2542.361 seconds )
Strings      2539.809

**Comment by spender-sandbox** [comment]
Do you have re2 installed?  Do you have nullterminated_only=yes under the [strings] heading of conf/processing.conf?

-Brad

**Comment by marek2003** [comment]
Hi Brad,
I Have not reinstalled cuckoo a part of installing/enabling malheur (a couple of weeks ago) and keepeing cuckoo updated with the latest commits.
here is my conf (I guess the default setting):
[strings]
enabled = yes
nullterminated_only = yes
minchars = 5
tks in advance
Marco

**Comment by spender-sandbox** [comment]
What's the output of:
python -c "import re2"

-Brad

**Comment by marek2003** [comment]
:-) re2 sorry I misunderstood.... :-)
here is my output
File "<string>", line 1, in <module>
ImportError: No module named re2

**Comment by spender-sandbox** [comment]
Install the re2 module, it's easy for the default re module to get into some terribly poor performance scenarios.

-Brad

**Comment by marek2003** [comment]
Yes, I guess I've to install it: 
thanks you so much. I'll let u know the result!
have a great weekend
Marco

**Comment by spender-sandbox** [comment]
BTW, just tested it here.  Analyzing the sample with re2 took .004 seconds :)

-Brad

**Comment by marek2003** [comment]
now it takes 0.002 :-)))))))))))
thank u
Marco
