### ISSUE TITLE
Submiting a zip with multiple samples only creates a task for one

### ISSUE THREAD

**Issue by seanthegeek** [spender-sandbox/cuckoo-modified#127]
The success page lists the right number of task IDs, but only one is actually created.

**Comment by KillerInstinct** [comment]
You using SQLite or something? Not getting this issue.

**Comment by seanthegeek** [comment]
PosgreSQL

**Comment by KillerInstinct** [comment]
Are any of the tasks pending? if we receive a task ID back to display on the web interface, they should have been inserted into the DB.

**Comment by seanthegeek** [comment]
Ah, never mind. It turns out that the tasks are added just were processed differently than I expected. For whatever reason, any .dot files I submit in a zip are themselves processed as an archive rather than an Office file, so that `vbaProject.bin` is processed on its own (which does not execute of course) for each file, rather than the .dot file as a whole.

Seperate bug. I shukld not write bug reports that late at night...
