### ISSUE TITLE
Hosting the API with Apache2

### ISSUE THREAD

**Issue by jonasdeblanger** [spender-sandbox/cuckoo-modified#129]
Hi,

Sorry if this is not the right place to look for an answer for my problem.
I've tried out the regular Cuckoo version 2.0 and the website and the API are running with Apache2.

I'm now trying out cuckoo-modified. The webserver runs fine with Apache2 but I can't seem to get the API running via Apache2.

Could someone point me in a direction on how to achieve this?

Thanks in advance,

Jonas

**Comment by doomedraven** [comment]
you have the api in /api not in another port as in cuckoo v2, check api tab in webgui for examples
here is like
/api

cuckoo v2
:8090/

**Comment by jonasdeblanger** [comment]
Yes, I do know about the API option on the website. But if I only configure the website to run with Apache2 this doesn't mean the API should work right?

**Comment by doomedraven** [comment]
should work because is part of webgui, not separated as in cuckoo v2

**Comment by jonasdeblanger** [comment]
O my god :). You are right. So I've been looking for an hour and a half while it already works. Thanks for help.

**Comment by doomedraven** [comment]
you are welcome :)
