### ISSUE TITLE
malheur,json,maec reports wont generate ONLY on some malware samples

### ISSUE THREAD

**Issue by limited-root** [spender-sandbox/cuckoo-modified#136]
i use cuckoo-brat to generate analysis reports for a malware dataset. it MOSTLY works fine and generates json reports, maec reports and malheur. but on some samples, i dont get any malheur; on some no maec; some even no json and no analysis/report folder. as it happens only on some samples, i was suspicious on anti-vm malwares. but then whats the reason that i get json report but not maec, or i get those but no malheur?
here i post logs regarding related errors, copied from cuckoo.log:
malheur:
`[lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory`
---
other errors:
---
`[lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Static":
Traceback (most recent call last):
  File "/etc/cuckoo/lib/cuckoo/core/plugins.py", line 197, in process
    data = current.run()
  File "/etc/cuckoo/modules/processing/static.py", line 1432, in run
    static = PortableExecutable(self.file_path, self.results).run()
  File "/etc/cuckoo/modules/processing/static.py", line 766, in run
    peresults["exported_dll_name"] = self._get_exported_dll_name()
  File "/etc/cuckoo/modules/processing/static.py", line 345, in _get_exported_dll_name
    return convert_to_printable(self.pe.get_string_at_rva(self.pe.DIRECTORY_ENTRY_EXPORT.struct.Name))
  File "/etc/cuckoo/lib/cuckoo/common/utils.py", line 137, in convert_to_printable
    if is_printable(s):
  File "/etc/cuckoo/lib/cuckoo/common/utils.py", line 110, in is_printable
    if c not in PRINTABLE_CHARACTERS:
TypeError: 'in <string>' requires string as left operand, not int'
-----
`[lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory`
-----

**Comment by spender-sandbox** [comment]
That's a bug with the latest version of pefile -- run some version from last year.

-Brad

**Comment by limited-root** [comment]
> That's a bug with the latest version of pefile -- run some version from last year.
are u referring to all three errors?
i dont care much about malheur, but i concern about 2 other reports

**Comment by limited-root** [comment]
> 

> ``

**Comment by spender-sandbox** [comment]
The pefile problem is cause of the static analysis problem, which can then cause cascading failures.

-Brad

**Comment by limited-root** [comment]
so i have to uninstall current version of pefile and install a version from 2015/ is it?

**Comment by limited-root** [comment]
there is no pefile after pefile-1.2.10-139 which is 2013. are u suggesting me to install that one? 3.4 and 3.28 are for 2016

**Comment by spender-sandbox** [comment]
Yes, that version should be fine.

-Brad

**Comment by limited-root** [comment]
there was some problems with installing old version of pefile. i followed the solution in their repository and replaced setup.py with another code. then i installed pefile and it seemed to be ok, but when i started analyzing, i got more errors:
1.
`[lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Static":
Traceback (most recent call last):
  File "/etc/cuckoo/lib/cuckoo/core/plugins.py", line 197, in process
    data = current.run()
  File "/etc/cuckoo/modules/processing/static.py", line 1432, in run
    static = PortableExecutable(self.file_path, self.results).run()
  File "/etc/cuckoo/modules/processing/static.py", line 766, in run
    peresults["exported_dll_name"] = self._get_exported_dll_name()
  File "/etc/cuckoo/modules/processing/static.py", line 345, in _get_exported_dll_name
    return convert_to_printable(self.pe.get_string_at_rva(self.pe.DIRECTORY_ENTRY_EXPORT.struct.Name))
  File "/etc/cuckoo/lib/cuckoo/common/utils.py", line 137, in convert_to_printable
    if is_printable(s):
  File "/etc/cuckoo/lib/cuckoo/common/utils.py", line 110, in is_printable
    if c not in PRINTABLE_CHARACTERS:
TypeError: 'in <string>' requires string as left operand, not int`

2.
`[lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MAEC41Report":
Traceback (most recent call last):
  File "/etc/cuckoo/lib/cuckoo/core/plugins.py", line 630, in process
    current.run(self.results)
  File "/etc/cuckoo/modules/reporting/maec41.py", line 84, in run
    self.addAnalyses()
  File "/etc/cuckoo/modules/reporting/maec41.py", line 869, in addAnalyses
    if self.options["static"] and self.results["static"]:
KeyError: 'static'`

**Comment by doomedraven** [comment]
1 https://github.com/spender-sandbox/cuckoo-modified/issues/103

means your pefile still broken

**Comment by limited-root** [comment]
103, u got exactly my converstion there lol.
come to telegram plz andey

**Comment by doomedraven** [comment]
@limited-root you banned in tg and you know why and i'm not andrey xD
don't replace setup.py just patch one line and you will get it works

**Comment by limited-root** [comment]
which line are u referring to?

**Comment by doomedraven** [comment]
in which you got error, you have everything in error msg

**Comment by limited-root** [comment]
line 8: import pefile
line 25: 'Intended Audience :: Science/Research',

what should i replace them with?

**Comment by limited-root** [comment]
line 8 in setup.py and line 25 in pefile.py
what should i replace them with?

**Comment by doomedraven** [comment]
lol just replace `__version__ = '1.2.10-%d' % int( __revision__ )` to `__version__ = '1.2.10`

**Comment by limited-root** [comment]
now unblock me in telegram and let me love u :dancers:

**Comment by doomedraven** [comment]
never

**Comment by limited-root** [comment]
`Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import pefile
  File "/home/administrator/Desktop/thesis final/pefile/pefile.py", line 25
    __version__ = '1.2.10-%d' % int( __revision__ ) to __version__ = '1.2.10
                                                     ^
SyntaxError: invalid syntax

not yet working. sorry if am dumb or anything, but am getting exhausted and i really need to start analysing a big dataset. can u tell me whats wrong`

**Comment by doomedraven** [comment]
lolo missed ' at the end

**Comment by limited-root** [comment]
ya obeshayu bolshe ne zadavatb typie voprosi,razblokiryu menya pojaluistaaaaaaa

**Comment by limited-root** [comment]
same
`python setup.py
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import pefile
  File "/home/administrator/Desktop/thesis final/pefile/pefile.py", line 25
    __version__ = '1.2.10-%d' % int( __revision__ ) to __version__ = '1.2.10'
                                                     ^
SyntaxError: invalid syntax`

**Comment by doomedraven** [comment]
my last response and i will totally ignore this and you

1 i'm not speaking russian 
2 you not patched script
3 never will unblock you

**Comment by limited-root** [comment]
now clean your comments. i removed all

**Comment by limited-root** [comment]
i found the solution, replace pefile and setup with these two edited ones:
`https://github.com/erocarrera/pefile/blob/4f685a2f8b732db4803a47ba42ece688f1e72a89/pefile.py`
and
`https://github.com/erocarrera/pefile/blob/4f685a2f8b732db4803a47ba42ece688f1e72a89/setup.py`

**Comment by stephenrauch** [comment]
Have you tried the soution which seems to be used by https://github.com/cuckoosandbox/cuckoo?  In their [ requirements.txt](https://github.com/cuckoosandbox/cuckoo/blob/master/requirements.txt) they have:

```
http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile
```

You might try adding the same here: [ requirements.txt](https://github.com/spender-sandbox/cuckoo-modified/blob/master/requirements.txt)

**Comment by limited-root** [comment]
havent tried that one as i didnt go for original cuckoo. the pefile version is correct, if its with edit developer did in 2015, then it should be fine.now am just getting some malheur classification errors which doesnt matter to me, everything else works fine :dancers:
