### ISSUE TITLE
Problems with MISP date

### ISSUE THREAD

**Issue by dforce** [spender-sandbox/cuckoo-modified#138]
I receive this error :
ValueError: time data '' does not match format '%Y-%m-%d'

When I check the results there is a field date which is empty.
Is it possible to add a check so it bypasses empty date fields ?

Thanks

**Comment by doomedraven** [comment]
@dforce is kinda weird what is empty, as there must be date for events, could you share one of the event responses?

**Comment by dforce** [comment]
This is what I have as result :
{0: {'info': '', 'level': '', 'url': 'https://misppriv.circl.lu/events/view/', 'iocs': ['time.windows.com'], 'eid': 0, 'date': ''}, u'3541': {'info': u'"TT Copy and Our New Order" / "TT Copy and New Order.scr"', 'level': u'1', 'url': 'https://misppriv.circl.lu/events/view/', 'iocs': ['246bb0f8d68a463fd17c235deb5491c0'], 'eid': u'3541', 'date': u'2016-03-18'}, u'1277': {'info': u'OSINT - A Look at Golroted/Hawkeye Keylogger', 'level': u'3', 'url': 'https://misppriv.circl.lu/events/view/', 'iocs': ['whatismyipaddress.com'], 'eid': u'1277', 'date': u'2015-06-10'}}

**Comment by doomedraven** [comment]
interesting you getting results for not existing event, as it has not event id, ok i think the simple solution it would be just ignore event ids 0(default if no id event returned, let me push update)

**Comment by dforce** [comment]
OK thanks

**Comment by doomedraven** [comment]
https://github.com/spender-sandbox/cuckoo-modified/pull/139

you can aplly this manually or wait until it will be marged

**Comment by dforce** [comment]
I have my misp.py in processing and not in reporting.

**Comment by doomedraven** [comment]
if you don't want update cuckoo right now, then just add that patch to your mips in processing, is just if which checks if there id

**Comment by dforce** [comment]
OK, just noticed the change.
My latest version was from yesterday morning.

**Comment by doomedraven** [comment]
if you wont apply patch manually you will need wait for this will be merged
https://github.com/spender-sandbox/cuckoo-modified/pull/139
