### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by DigiAngel** [spender-sandbox/cuckoo-modified#156]
Getting this when I attempt a javascript run:
~~~
Error: Analysis failed: The package "modules.packages.js" start function encountered an unhandled exception: Config instance has no attribute 'file_type'
~~~

Anything I can do to troubleshoot this?  And thanks so much for this version of cuckoo.

**Comment by spender-sandbox** [comment]
Are you using the latest version?  Have you modified it at all?  I don't see how that issue could be happening, since the code that I believe would be triggering that failure for you was added here:
https://github.com/spender-sandbox/cuckoo-modified/commit/634a4319a4150a2f44d84a8f34cadc3fa35ba61f

with no reported issues since then.

-Brad

**Comment by DigiAngel** [comment]
Thanks for the quick response.  I'll do a git pull and try again.  It's usually some malicious obfuscated js file I'm testing.  Thank you.

**Comment by DigiAngel** [comment]
Just pulled..here's what I got:
~~~
From https://github.com/spender-sandbox/cuckoo-modified
   e135915..b86a72a  master     -> origin/master
Updating e135915..b86a72a
Fast-forward
 modules/processing/dropped.py      | 5 ++++-
 modules/reporting/malheur.py       | 3 +++
 web/api/views.py                   | 7 ++++++-
 web/templates/analysis/report.html | 4 ++++
 4 files changed, 17 insertions(+), 2 deletions(-)
~~~

Trying file now.

**Comment by DigiAngel** [comment]
Hrmm....I think I may know why....the file is borked:
https://  . servicoonline . egnyte . com /dd/ jgfwvkoQE1

the first like...224 bytes are most definitely NOT javascript.  Still analysing.

**Comment by DigiAngel** [comment]
But upon completion:
~~~
Error: Analysis failed: The package "modules.packages.js" start function encountered an unhandled exception: Config instance has no attribute 'file_type'
~~~

**Comment by DigiAngel** [comment]
Yep...confirmed that borked file = borked analysis..which totally makes sense.  For those following at home the offending url (analysis) is here:
~~~
http://vurldissect.co.uk/?url=3694496
~~~
Note the gobblegook at the bottom of the headers...closing this out and sorry for the noise.

**Comment by spender-sandbox** [comment]
Still shouldn't produce that error.  Can you screenshot the report page showing the identified file type, etc?

-Brad

**Comment by DigiAngel** [comment]
Can do..here's the official "from the log" line:
2016-05-30 07:47:39,683 [lib.cuckoo.core.scheduler] ERROR: Analysis
failed: The package "modules.packages.js" start function encountered an
unhandled exception: Config instance has no attribute 'file_type'
Attachment screenshot enclosed...and thanks again for all your work on
this.
