### ISSUE TITLE
DNS request missing

### ISSUE THREAD

**Issue by dforce** [spender-sandbox/cuckoo-modified#157]
Hi all,

When running a sample I see that I am missing some DNS request.
See https://www.virustotal.com/nl/file/927363c83e69ab898879173136e9f0894550ba54439421b729ccfc5e3f1988f3/analysis/1464679104/

I got the request for whatismyipaddress but I am missing mail.puresteeldesigns.com. This request is not solving to any IP address at the moment but I would like to see this in the results.
Even running the official version of cuckoosandbox I see these requests.

Can this be solved ?

**Comment by doomedraven** [comment]
at last can you share pcap, analysis log, etc without see nothing it difficult to say something, as it can be just your fail, or sample not executed correctly or a lot of other things

**Comment by dforce** [comment]
Can be found here
https://app.box.com/s/6umgrnwvdcefinc7jzzw4rhza8zluqot
password : infected

**Comment by doomedraven** [comment]
mail.puresteeldesigns.com is not in logs,pcap, so it not connected, or analysis finished too quick or something like that

**Comment by dforce** [comment]
Is there a way to solve this, I don't think that I have to reset the timeout each time when I do an analysis ?

**Comment by doomedraven** [comment]
try set highest timeout and enforce it, is difficult to say what is wrong with your analysis

**Comment by dforce** [comment]
Changed timeouts in cuckoo.conf and now it's working.
