### ISSUE TITLE
file not appers in dropped, but is presented in analysis

### ISSUE THREAD

**Issue by doomedraven** [spender-sandbox/cuckoo-modified#158]
Hello all

* Process Tree
```
wscript.exe 2700 "C:\Users\X\AppData\Local\Temp\X.js"
Drops:
X.exe 3096
```
* From apicalls logs
* `NtQueryAttributesFile	FileName: C:\Users\X\AppData\Local\Temp\X.exe 
success	0x00000000`

* and I see full behaviour of that x.exe in behaviour tab, but in dropped in not appers, any idea? i can see part of MZ... in buffer but as it cutter i can't restore sample 

```
2016-05-31 08:31:59,703	3100	0x0011088b
0x00110444	RtlDecompressBuffer	UncompressedBufferLength: 0x0001b200 
UncompressedBufferAddress: 0x00350000 
UncompressedBuffer: MZ\x90\x00\x03\x00\x00\x00\x04\x00\x00\x00\xff\xff\x00\x00\xb8\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe8\x00\x00\x00\x0e\x1f\xba\x0e\x00\xb4	\xcd!\xb8\x01L\xcd!This program cannot be run in DOS mode. 
```

* can be this related? `cmd.exe 3056 /C del /Q /F "C:\Users\X\AppData\Local\Temp\X.exe"`

PS
````
2016-05-31 08:31:59,468	3092	0x00000000
0x00000000	NtCreateFile	ShareAccess: FILE_SHARE_READ 
FileName: C:\Users\X\AppData\Local\Temp\X.exe 
DesiredAccess: FILE_READ_ATTRIBUTES|READ_CONTROL|SYNCHRONIZE 
ExistedBefore: yes 
StackPivoted: no 
CreateDisposition: FILE_OPEN 
FileHandle: 0x000003dc 
FileAttributes: 0x00000000 
```

**Comment by spender-sandbox** [comment]
Wasn't updated to the latest version? ;)

-Brad

**Comment by doomedraven** [comment]
i always update before open issue, i lost the hash, and as dev server analysis data was cleaned, can't find it and reproduce, if will return have this issue will reopen it
