### ISSUE TITLE
Tor Proxy Errors

### ISSUE THREAD

**Issue by fulco** [spender-sandbox/cuckoo-modified#165]
Not sure if it's better to put this here, or in routetor's issues.  I apologize in advance if this has been addressed, but I have searched and can't seem to find it and I'm pretty sure it's a misconfiguration on my part.  When submitting a new Cuckoo job and selecting "Enable Tor transparent proxy", I get the following error:

`2016-06-01 10:57:51,258 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 24650 (interface=vboxnet0, host=192.168.56.29, dump path=/home/****/storage/analyses/302/dump.pcap)`

`2016-06-01 10:57:51,259 [lib.cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
Traceback (most recent call last):
  File "/usr/sbin/torstart", line 31, in <module>
    client.sendto("start {0}".format(args.address), SOCKPATH)
socket.error: [Errno 13] Permission denied`

`2016-06-01 10:57:51,286 [modules.auxiliary.tor] INFO: Started Tor transparent proxy for 192.168.56.29
`
Any suggestions on what I'm missing would be greatly appreciated.

**Comment by doomedraven** [comment]
How you executed routetor?

**Comment by fulco** [comment]
sudo /usr/sbin/routetor &
Per the instructions in the installation readme (https://github.com/seanthegeek/routetor/blob/master/README.md) 


On Jun 1, 2016, at 11:55, doomedraven <notifications@github.com> wrote:

How you executed routetor?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



Jason

**Comment by seanthegeek** [comment]
Hello,

It looks like you started routetor, but the user that you are running cuckoo as does not have permission to write to the socket created by routetor. Are you running cuckoo as a user named cuckoo? If not, you will need to change the routetor config.

**Comment by fulco** [comment]
Perfect!  That was it.  Thank you.  We had renamed the user and group for internal audit. I added the `-g=` and all is good.
