### ISSUE TITLE
Submit File / URL Analysis with API and use TOR

### ISSUE THREAD

**Issue by hexlax** [spender-sandbox/cuckoo-modified#166]
I have verified that web submissions of samples with the checkbox enabled for TOR are working correctly; however, there does not seem to be a way to enable TOR via the API. I only glanced over the code - is this not an option available with the API?

Utilizing this curl call to test API and TOR:
`curl -F url="https://icanhazip.com" -F tor="on" http://cuckoo.local/api/tasks/create/url/`

Appreciate any help in troubleshooting this issue. Thanks!

**Comment by doomedraven** [comment]
You nned set options argument to tor=yes -F options="tor=yes" something like this

**Comment by hexlax** [comment]
Yep, thanks @doomedraven - that was it. I used this curl command and verified screenshot output is utilizing TOR now:

`curl -F url="http://icanhazip.com" -F options="tor=on" http://cuckoo.local/api/tasks/create/url/`

Closing since this was not a bug...
