### ISSUE TITLE
no report for some samples and cuckoo stoppes after 22 analysis‌(dataset is 23000)

### ISSUE THREAD

**Issue by limited-root** [spender-sandbox/cuckoo-modified#167]
when i start analysis, when it reach to sample number 23, VMs DOS window doesnt generate anything anymore. VMs are up, DOS windows are open, but cuckoo stoppes generating report.
also among those 23 samples, some are limited to pcap only, some binary and pcap, some got reports but no malheur and some with json.
there is no error in logs beside this errors which happens during analysis:
`2016-06-05 23:14:31,357 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "copies_self":
Traceback (most recent call last):
  File "/etc/cuckoo/lib/cuckoo/core/plugins.py", line 351, in process
    data = current.run()
  File "/etc/cuckoo/modules/signatures/copies_self.py", line 39, in run
    for drop in self.results["dropped"]:
KeyError: 'dropped'
2016-06-05 23:14:31,507 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "polymorphic":
Traceback (most recent call last):
  File "/etc/cuckoo/lib/cuckoo/core/plugins.py", line 351, in process
    data = current.run()
  File "/etc/cuckoo/modules/signatures/polymorphic.py", line 47, in run
    for drop in self.results["dropped"]:
KeyError: 'dropped'`

but when on sample 23, cuckoo stoppes analysis, no error is generated. 
in var/log/sys.log i have:
`Jun  5 23:30:49 server kernel: [10450.257328] device wlan0 left promiscuous mode
Jun  5 23:30:49 server kernel: [10450.963982] vboxdrv: ffffffffc14b7020 VBoxDDR0.r0
Jun  5 23:30:49 server kernel: [10450.965831] vboxdrv: ffffffffc02ad020 VBoxDD2R0.r0
Jun  5 23:30:52 server kernel: [10454.019254] device wlan0 entered promiscuous mode
Jun  5 23:34:05 server kernel: [10647.326370] nspr-3[8638]: segfault at 44 ip 0000000000000044 sp 00007fb8e4020628 error 14 in VirtualBox[400000+8000]
Jun  5 23:37:19 server kernel: [10840.639304] vboxnetflt: 283304 out of 350798 packets were not sent (directed to host)
Jun  5 23:48:02 server NetworkManager[1184]: <warn> nl_recvmsgs() error: (-33) Dump inconsistency detected, interrupted`

and in kern i have:
`Jun  5 23:17:37 server kernel: [ 9657.866620] perf interrupt took too long (2503 > 2500), lowering kernel.perf_event_max_sample_rate to 50000
Jun  5 23:17:43 server kernel: [ 9664.371219] nspr-2[5489]: segfault at 0 ip           (null) sp 00007f6a0653c648 error 14 in VirtualBox[400000+8000]
Jun  5 23:27:34 server kernel: [10255.924371] nspr-3[7356]: segfault at 34 ip 0000000000000034 sp 00007fcf3a5f2628 error 14 in VirtualBox[400000+8000]
Jun  5 23:30:49 server kernel: [10450.257328] device wlan0 left promiscuous mode
Jun  5 23:30:49 server kernel: [10450.963982] vboxdrv: ffffffffc14b7020 VBoxDDR0.r0
Jun  5 23:30:49 server kernel: [10450.965831] vboxdrv: ffffffffc02ad020 VBoxDD2R0.r0
Jun  5 23:30:52 server kernel: [10454.019254] device wlan0 entered promiscuous mode
Jun  5 23:34:05 server kernel: [10647.326370] nspr-3[8638]: segfault at 44 ip 0000000000000044 sp 00007fb8e4020628 error 14 in VirtualBox[400000+8000]
Jun  5 23:37:19 server kernel: [10840.639304] vboxnetflt: 283304 out of 350798 packets were not sent (directed to host)`

**Comment by spender-sandbox** [comment]
This would be an issue with VirtualBox, I don't see how it has anything to do with this version of Cuckoo.

-Brad

**Comment by limited-root** [comment]
not generating report for some samples, is related to virtualbox also?
what can be the problem?
and am using bridged, would that make any problem if i dont use host-only ?
