### ISSUE TITLE
No Detection for specific JS

### ISSUE THREAD

**Issue by marek2003** [spender-sandbox/cuckoo-modified#168]
Hello,
I was submitting some samples to  Cuckoo and I've noticed that some new JS (probably with obfuscated code) weren't recognized as malicious at all and no signatures are triggered .
I did the same on Malwr and here is the output (https://malwr.com/analysis/N2VjNjkzYjhkNDg0NDEzYjg0YWM3MDI3MTcwMWEzOGY/)
here is on VT: (https://www.virustotal.com/en/file/cf6d52653c47d62036ea341289eec9f106a9328d4f5643242699c41fd669f247/analysis/1465201132/)
Any advice and suggestions will be greatly appreciated
Marco

**Comment by seifreed** [comment]
Seems, the JS have some problem..

![image](https://cloud.githubusercontent.com/assets/1843119/15922614/f360e118-2e28-11e6-9de0-737b867fb0b8.png)
