### ISSUE TITLE
Cuckoo is not following properly wscript executions

### ISSUE THREAD

**Issue by seifreed** [spender-sandbox/cuckoo-modified#170]
Hi,

JS downloaders like Nemucod or Nymaim are not correctly analyzed by Cuckoo.

One example with the hash: 5a8ba442a437b1a638536daae2a28a61

The report is not showing network requests:

![image](https://cloud.githubusercontent.com/assets/1843119/15922730/9fad0d7a-2e29-11e6-829c-70708abd6f5e.png)

But, in the behaviour TAB, you can see the API calls requests and the URL contacted:

![image](https://cloud.githubusercontent.com/assets/1843119/15922768/c6466670-2e29-11e6-8cfe-7865a3305362.png)

![image](https://cloud.githubusercontent.com/assets/1843119/15922781/d603f1a4-2e29-11e6-85b3-5813632bfd82.png)

![image](https://cloud.githubusercontent.com/assets/1843119/15922793/e6a2f460-2e29-11e6-8b43-d4707e9db213.png)

Regards,

**Comment by KillerInstinct** [comment]
I think this may be an issue with your sniffer setup. Mine works just fine for this sample:

http://i.imgur.com/YXq4UAi.png
http://i.imgur.com/YctBUdU.png

**Comment by seifreed** [comment]
Hi,

I tried with the last version of cuckoo and now works..

Thanks for all
