### ISSUE TITLE
triggering on doc close 

### ISSUE THREAD

**Issue by mallorybobalice** [spender-sandbox/cuckoo-modified#200]
seeing a few samples in the wild recently that trigger macros on doc close instead of open. except they don't since in the guest they (the office processes) never get closed. 

what's the way to make child vms close word /excel etc after a timeout, or as 'last resort' before the vm timeout? (and to manage the timeout vs vm getting reset timeout).
happy to enable a generic 'terminate package app' type setting if there

**Comment by mallorybobalice** [comment]
hmmm, am i thinking of 

https://github.com/spender-sandbox/cuckoo-modified/blob/master/conf/cuckoo.conf


terminate_processes = off->on


[timeouts]

default = 120

critical = 60


?? or will that not work?

**Comment by mallorybobalice** [comment]
hmmm the terminate process option definitely doesn't help here . 
any ideas?

**Comment by spender-sandbox** [comment]
We already had support for it, but it only worked for older Office versions.  I just committed a change that will handle it for newer Office as well.

-Brad

**Comment by mallorybobalice** [comment]
Hmm no wonder I thought I saw it in human py. (A while back )

Right, so, if I'm reading it correctly err It'll try it 30 after opening? Once. By window title. Word excel PowerPoint, if file type submitted matches? . 
This is on no way related to the analysis timeouts in cuckoo. Conf, except should be enough time for 30s plus a bit more for obvious reasons, correct ?

**Comment by mallorybobalice** [comment]
Sweet, thank you Brad
