### ISSUE TITLE
Timer based Sleep Evasion

### ISSUE THREAD

**Issue by garanews** [spender-sandbox/cuckoo-modified#212]
http://www.joesecurity.org/reports/report-58258b89e076c4d378436f3b03682402.html
http://joe4security.blogspot.it/
How to manage this samples?
"The cookbook accelerates the local system time and simulates 30 minutes time shift in 30 seconds. Since the VBA timer is based on the local system time this will bypass this evasion:"

**Comment by spender-sandbox** [comment]
Their analysis is a bit wrong -- I'll write something up that will deal with this properly.

-Brad

**Comment by spender-sandbox** [comment]
There, should work just fine now.  Thanks for bringing it to my attention.

-Brad

**Comment by seanthegeek** [comment]
@spender-sandbox I'm curious, where was their analysis wrong?

**Comment by spender-sandbox** [comment]
It's mentioned in my commit message ;)

-Brad
