### ISSUE TITLE
Problem analyzing wsf file

### ISSUE THREAD

**Issue by dforce** [spender-sandbox/cuckoo-modified#215]
When submitting file and let cuckoo detect automatically the analysis package, it wasn't recognized. Cuckoo is adding automatically the extension ".html".
The file I received has the name "profile-caca..wsf". Thought the problem was the 2 points before "wsf", so I changed the name to "profile-caca.wsf" but didn't solved the problem.

Selecting the analysis package "wsf" myself, solved the problem.

File was submitted to VirusTotal and result can be found here 
https://www.virustotal.com/en/file/21607d92467ce8f7f5f93d8814418506ba7e8cee0f64f67b3a084af0414b680c/analysis/1468407106/

Can you tell me what went wrong during the automatically detection of the analysis package ?

Thanks

**Comment by spender-sandbox** [comment]
What was the detected filetype?

-Brad

**Comment by dforce** [comment]
Type within analysis result is "HTML document, ASCII text, with CRLF, LF line terminators".

**Comment by spender-sandbox** [comment]
That's most likely why then.  I'll reorder the checks so .wsf gets priority.

-Brad

**Comment by dforce** [comment]
Ok, thanks, because there is a big difference within the results of the analysis.

**Comment by spender-sandbox** [comment]
Should be fixed now.

-Brad

**Comment by dforce** [comment]
Problem solved.
Thanks
