### ISSUE TITLE
MIsp Report

### ISSUE THREAD

**Issue by marek2003** [spender-sandbox/cuckoo-modified#218]
Hi All,
I'm testing Cuckoo with MIsp integration and it works awesomely! The only problem is when i try to download Misp report from Cuckoo web interface I get a "file not found" . Infact I don't have any "misp" data on storage folder.
Someone can help me?
tks a lot !

**Comment by doomedraven** [comment]
checking

**Comment by doomedraven** [comment]
ok so, for make it works you must have activated extend_context = yes
https://github.com/spender-sandbox/cuckoo-modified/blob/master/modules/reporting/misp.py#L226 <- see this

if you have that option activated you can download report from web :)

let me know if that works for you, i will push better expanation in conf

**Comment by marek2003** [comment]
It works! thanks a lot for your support! :-)))))))

**Comment by doomedraven** [comment]
@marek2003 you are welcome :)
please close issue as it resolved :P
