### ISSUE TITLE
Problems analyzing dlls

### ISSUE THREAD

**Issue by dforce** [spender-sandbox/cuckoo-modified#239]
When adding dlls the packages selected automatically is "exe" and not "dll" and therefor analysis is not completely run. When selecting it manually there is no problem.

This is when I get doing the 'file' command :
embedded.dl_:  PE32 executable (native) Intel 80386, for MS Windows
embedded.dl_:  PE32+ executable (native) x86-64, for MS Windows

What went wrong and how can this be solved ?

Thanks

**Comment by spender-sandbox** [comment]
Those are native binaries and likely not DLLs -- they won't run on booted windows.  If you change the subsystem in the PE header to GUI or console, you can probably trick those to run in Cuckoo.

-Brad

**Comment by dforce** [comment]
Ok, Thanks
