### ISSUE TITLE
Physical Machinery error

### ISSUE THREAD

**Issue by hexlax** [spender-sandbox/cuckoo-modified#253]
Howdy folks, first let me say thank you to all the volunteers who make this fork my favorite OS project! So here it goes: I'm attempting to get an instance with the physical machinery working and am running in to an error. 

Here is the debug log:
```
2016-08-20 20:30:08,615 [modules.machinery.physical] DEBUG: Getting status for machine: physical1.
2016-08-20 20:30:08,625 [modules.machinery.physical] DEBUG: Received unknown exception: 'NoneType' object has no attribute 'get_status'.
2016-08-20 20:30:08,625 [root] CRITICAL: CuckooCriticalError: Physical machine is currently offline
```

Any ideas?

**Comment by hexlax** [comment]
I verified that I am able to control the physical machine with the net commands from the host (Ubuntu) workstation. Could this be due to the updated agent running on the guest computer?

**Comment by spender-sandbox** [comment]
It's because that physical code could have never worked to begin with.  It creates a GuestManager which has a 'server' member which is None-initialized, which it then immediately tries to use.

-Brad

**Comment by spender-sandbox** [comment]
Should be fixed now.

-Brad

**Comment by hexlax** [comment]
Awesome - thanks Brad & @jbremer 
I'll test this soon and let you know how it turns out.

**Comment by hexlax** [comment]
Looks good - thanks gents!

Closing issue...
