### ISSUE TITLE
[lib.cuckoo.core.scheduler] ERROR: Analysis failed: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by garanews** [spender-sandbox/cuckoo-modified#26]
How fix the error:
ERROR: Analysis failed: maximum recursion depth exceeded
?
Someone was aleary speaking here:
https://github.com/cuckoosandbox/cuckoo/issues/725

Thanks

**Comment by spender-sandbox** [comment]
I could fix the symptom, but the actual problem seems to be that your guest isn't able to reach the resultserver to send anything back.

**Comment by garanews** [comment]
![capturez](https://cloud.githubusercontent.com/assets/16938405/12645710/2169f0ce-c5cc-11e5-9fe2-96f5410f8eb9.PNG)
You see, I have 10 guests, sometime this issue happens, not always.
And same guest, sometime is ok and sometime is giving that error.

**Comment by spender-sandbox** [comment]
Give that new fix a try, thanks!

-Brad
