### ISSUE TITLE
KeyError suricata

### ISSUE THREAD

**Issue by eoinmiller-sfdc** [spender-sandbox/cuckoo-modified#27]
Did a fresh install and the web interface fails when attempting to look at the reports with the following error:

KeyError at /analysis/1/
'suricata'
Request Method:	GET
Request URL:	http://192.168.1.5:8000/analysis/1/
Django Version:	1.6.1
Exception Type:	KeyError
Exception Value:	
'suricata'
Exception Location:	/home/cuckoo/cuckoo-modified/web/analysis/views.py in report, line 672
Python Executable:	/usr/bin/python
Python Version:	2.7.6

**Comment by spender-sandbox** [comment]
Should be fixed now, let me know if it's not.

-Brad

**Comment by eoinmiller-sfdc** [comment]
Confirmed fixed, thanks!
