### ISSUE TITLE
Digital Signature Static Processing Failure

### ISSUE THREAD

**Issue by keithjjones** [spender-sandbox/cuckoo-modified#278]
Has anyone seen this?  I'm running the latest cuckoo-modified on Mac OSX Yosemite.

It appears to be related to m2crypto and the digital signature portion.  I'm analyzing the standard 32-bit version of signtool.exe here, and it crashes.  When I analyze a file that does not have a signature, it does not crash.  

BTW DigiSig.json is populated just fine.  It's almost like there is a parsing error on that data?

I have been unable to figure out the issue.  Any advice is appreciated.  If you need any more info, please let me know.

Thanks!

```
2016-09-08 11:10:11,513 [lib.cuckoo.core.guest] INFO: cuckoo1: analysis completed successfully
2016-09-08 11:10:17,194 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Static":
Traceback (most recent call last):
  File "/Source/cuckoo-modified/lib/cuckoo/core/plugins.py", line 197, in process
    data = current.run()
  File "/Source/cuckoo-modified/modules/processing/static.py", line 1443, in run
    static = PortableExecutable(self.file_path, self.results).run()
  File "/Source/cuckoo-modified/modules/processing/static.py", line 787, in run
    peresults["digital_signers"] = self._get_digital_signers()
  File "/Source/cuckoo-modified/modules/processing/static.py", line 721, in _get_digital_signers
    bio = BIO.MemoryBuffer(signature)
  File "/Source/Python/lib/python2.7/site-packages/M2Crypto/BIO.py", line 183, in __init__
    "data must be bytes or None, not %s" % (type(data).__name__, ))
TypeError: data must be bytes or None, not bytearray
Exception AttributeError: "'MemoryBuffer' object has no attribute '_pyfree'" in <bound method MemoryBuffer.__del__ of <M2Crypto.BIO.MemoryBuffer object at 0x107abc110>> ignored
```

**Comment by jgajek** [comment]
This looks like another Python 2to3 issue in the pefile module, like #103.  I will look into a real fix, but you can try reverting to an older release of the pefile module.

**Comment by keithjjones** [comment]
@jgajek thanks for the quick answer!  Any particular version of the pefile module you recommend?

**Comment by jgajek** [comment]
Not sure exactly when the 2to3 changes went in, but you should be safe with a version from last year.

**Comment by keithjjones** [comment]
Update: I installed the specific version called out in the requirements, and I no longer get that error.  I found it here https://github.com/erocarrera/pefile/releases/tag/pefile-1.2.10-139 

I had to do a little code editing for it to work (changing the version in the header to be hard coded to the real version of the tarball, but not much else).  Then it installed.

However, cuckoo-modified seems to run but not put any output to the created HTML file regarding the information within the signature.  Not sure why.  The DigiSig.json file is still correct.  I get a signature hit with "Presents an Authenticode digital signature" in green, but no detailed signature data is added to the HTML.  

How do you output the contents of the signature into the HTML report?

I may be missing something small, but I can't figure out what it is.  Any advice is appreciated.  Thanks @jgajek

**Comment by doomedraven** [comment]
That git version it also broken install pefile2 from pip or download that version feom google code

**Comment by jgajek** [comment]
The API contract for the pe.write() function in the pefile module was
broken in this commit from March 28, 2016:
https://github.com/erocarrera/pefile/commit/971da4ff74ff6d9ba7ef7790dd6526824629d223

The write() function is documented as returning a 'str' (if no file to
write to is specified), but in that commit it was changed to return a
bytearray object instead, without regard for the problems this would cause
for apps that rely on the return value being a 'str'.  I will submit a PR
shortly to work around this blunder.

**Comment by keithjjones** [comment]
Thanks @jgajek 

@doomedraven pefile2 installed, still no signers listed in the HTML output.  It just says "Presents an Authenticode digital signature" in green without any of the signers information.  And that signature is not clickable.

Thanks for lending a hand and so quickly!  I've been putting quite of few hours into this issue.

**Comment by keithjjones** [comment]
@jgajek this push worked.  I tested it with the latest pip install pefile.

I have yet to figure out how to get the digital signature output into the HTML report.  Any guidance on that?  I see there are all sorts of tags in /web/templates/analysis/static/_pe32.html to output this data, yet it is not outputting it.

Thanks!

Take care,
Keith

**Comment by keithjjones** [comment]
Ok, I've discovered that the HTML summary shows a little more information on the signatures than the "big html" output, but not all of it.  It appears not to be in the report template at all, even though it is in those components I identified above.

**Comment by jgajek** [comment]
I'm seeing the digital signature info in the Static Analysis tab.  Perhaps you are missing one of the required python modules?

**Comment by keithjjones** [comment]
Are you using the web interface or the HTML report @jgajek ?  From what I can tell, they use different templates.

**Comment by jgajek** [comment]
Ah, sorry.  I'm using the Django web interface.

**Comment by KillerInstinct** [comment]
The standalone web interface is pretty much unsupported in this repo. Would suggest using the Django one.

**Comment by keithjjones** [comment]
Ah hah.  That's what I suspected.  I'll have to hook it up.

**Comment by spender-sandbox** [comment]
Not true!  I do try to keep the html / django versions synced up, since the htmlsummary is a subset of the normal html pages, which can be used for the pdf conversion.  This specific thing might have just slipped through the cracks.  Usually it's just a simple copy+paste and small conversions to bring something from the django templates over to the html versions.

-Brad

**Comment by jgajek** [comment]
@keithjjones I'm running the Django interface behind an nginx reverse proxy.  For a sample setup you can refer to https://github.com/jgajek/cuckoo-docker

**Comment by keithjjones** [comment]
Got the web server running.  Awesome!

Interesting results - I changed a string in signtool.exe, called it notsigntool.exe, uploaded and cuckoo-modified is still saying the signature is valid.  I can supply the EXE I modified if you want to try it.  You would assume the signature would not validate since the contents changed, right?  Usually with signtool.exe you have to specify /pa and /all to get it to show you the signature is not valid.

**Comment by jgajek** [comment]
Depends where you changed the string.  Not all the contents of the binary are hashed when computing the Authenticode signature.

**Comment by keithjjones** [comment]
True.  But if I run signtool /pa /all notsigntool.exe it will fail, but signtool /pa /all signtool.exe it will not.  I just picked a random string near the end.  If I remember right, for "Corporation" in "Microsoft Corporation" I changed a letter to see if signtool would tell me the binary was different.  

Here's an example I ran:

```
C:\Users\kjones>Desktop\signtool.exe verify /pa /all c:\MyDir\signtool.exe
File: c:\MyDir\signtool.exe
Index  Algorithm  Timestamp
========================================
0      sha1       Authenticode
1      sha256     RFC3161

Successfully verified: c:\MyDir\signtool.exe

C:\Users\kjones>Desktop\signtool.exe verify /pa /all c:\MyDir\notsigntool.exe
File: c:\MyDir\notsigntool.exe
Index  Algorithm  Timestamp
========================================
0      sha1       Authenticode
SignTool Error: WinVerifyTrust returned error: 0xC000A000

Number of signatures successfully Verified: 1
Number of errors: 1
```

**Comment by jgajek** [comment]
I agree that /pa is the correct policy to use, since otherwise signtool will use the driver verification policy.  What I don't understand is why a modified file would successfully validate without /pa, but not with /pa.  As far as I know, the driver verification policy (no /pa) is more strict.

**Comment by keithjjones** [comment]
@jgajek I used /pa in both cases so that is not a factor.  I *think* /pa without /all just looking at the certificates while /all is looking at every "file" within the file, and that's why it will show the change.  I *think* if I don't change the signature, but change the file, that signtool /pa will miss it.  I'm not 100% sure on this.  That's why I'm playing around to see what the output is.  I was pretty surprised to not get a warning on such a change.  I'm happy to share the altered EXE files I'm testing with, but it's as simple as finding an obvious string and changing a letter deep in the file.

**Comment by jgajek** [comment]
My interpretation of the /all switch is that if there are multiple signatures (e.g. a signature with an SHA-1 hash and a signature with an SHA-256 hash), then both will be verified.  Without the /all switch, only one of them (the primary?) will be verified.  So your file tampering should produce an error in both cases.  But I will do some testing myself.

**Comment by keithjjones** [comment]
Yes, let's figure this out @jgajek because this just turned my whole world upside down in how I understood how the tool worked.  :)

I think there are different "files" in there, and that's what I'm seeing.  But again, I'm just educated guessing.

**Comment by jgajek** [comment]
So I took the signtool.exe binary (without any modifications) and ran it through Cuckoo's digisig verification.  As expected, it verifies without any errors.  Then I loaded it up in IDA Pro and changed a machine instruction in the .text segment.  Now Cuckoo's digisig verification reports "WinVerifyTrust returned error 0x80096010 The digital signature of the object did not verify."  So I couldn't replicate your results.

Can you share your binaries?

**Comment by doomedraven** [comment]
i didn't have any problem with this one

md5sum signtool.exe
4debf08f5d6d62f15a88d452336c2d55  signtool.exe

**Comment by keithjjones** [comment]
Sure thing.  https://github.com/keithjjones/testing

It sounds like you went way above and beyond what I did.  I just looked for an ascii character and changed it deep in the file to get the file hash to change.  I expected any change, anywhere, would cause a signature failure.

Let me know what you come up with.

Thanks!

Take care,
Keith

**Comment by keithjjones** [comment]
@jgajek and @doomedraven also, signtool's output says:

```
Other options:
/all        Verify all signatures in a file with multiple signatures.
```

So there are multiple signatures per file.  Without the /all signtool doesn't check all of them, at least in that binary I just uploaded for you.  I don't understand that part.  It looks like whatever I modified may have changed something in the timestamp certificate because of the RFC3161 designation in the original file.

**Comment by jgajek** [comment]
As far as I can tell, the string you changed (from Microsoft Corpor<a>tion to Microsoft Corpor<o>tion) is part of the Certificate Table, which is omitted from the Authenticode hash calculation (refer to "Calculating the PE Image Hash" in http://download.microsoft.com/download/9/c/5/9c5b2167-8017-4bae-9fde-d599bac8184a/authenticode_pe.docx).

So it won't invalidate the PE image hash, but it will invalidate the certificate hash inside one of the certificates associated with the secondary SHA-256 Authenticode signature.  Without the /all option, that certificate chain is not verified by signtool.

Try changing some bytes towards the middle of the binary -- these should be covered by the Authenticode hash calculation.

**Comment by keithjjones** [comment]
Will do.  Thanks for the second look @jgajek !
