### ISSUE TITLE
Distributed Cuckoo

### ISSUE THREAD

**Issue by keithjjones** [spender-sandbox/cuckoo-modified#284]
I'm forwarding this issue from the old repository to here.  I was looking into this today and it looks like cuckoo-modified doesn't have the same capabilities?

https://github.com/brad-accuvant/cuckoo-modified/issues/290

Thanks!

**Comment by doomedraven** [comment]
in mod is much better yet, the original has some improvements but it just return json or html, here it will return analysis with files and show all data in master webgui

**Comment by doomedraven** [comment]
https://github.com/spender-sandbox/cuckoo-modified/blob/master/docs/book/src/usage/dist.rst

**Comment by keithjjones** [comment]
:+1: Thanks!

**Comment by doomedraven** [comment]
feel free to ping me if you have any issue

**Comment by keithjjones** [comment]
Will do.  I think we'll be trying to work with it in the upcoming weeks.  I really appreciate the quick response.

**Comment by doomedraven** [comment]
i have it in production for almost 2 month, so all bugs which we saw we fixed, it now stable for a lot of time ago

so if you see any issue let me know
