### ISSUE TITLE
How to use cuckoo-modified?

### ISSUE THREAD

**Issue by Monkie1990** [spender-sandbox/cuckoo-modified#286]
This may be a stupid question but I'm new to this, how do you run / install cuckoo-modified? I've already cloned it but am not sure of the next steps.... readme file was too helpful either

**Comment by doomedraven** [comment]
Check documentation folder

**Comment by jowayow** [comment]
Read and re-read the documentation please. To get a feel, run `cuckoo.py` (of course you should have Python installed first). This main script just uses all other files found within the directory. As to how to do it and what to know, again, the documentation.

**Comment by kevross33** [comment]
Hi,

There is documentation but basic high points are:
1) Follow documentation and make sure all dependencies and extras are installed (software and python modules
2) Setup your Windows VM and make sure base OS and it can communicate (ideally isolate it in a virtual network and deal with Internet when you are more experienced with it). Pop the agent.py on it and run that (you can use .pyc and make hidden later but for now you want to see errors).
3) Configure VM in the settings in the conf folder and other settings in there (documentation and what you want) - Also make sure you have mongod running on system
4) go into utils folder and run command "yes yes | python community.py -s" to install all the signatures and answer yes to do so.
5) In cuckoo root folder run python cuckoo.py and make sure it runs, now also run in the cuckoo folder go into web folder and run "python manage.py runserver 127.0.0.1:8080" which will run the web interface on that address so you can reach it and will connect to the mongod instance (make sure this is configured in reporting too in the config files in the conf folder).
6) Check on submit you can see the VMs as options to submit to and as a test download software and run it (without human intervention). My fave is putty.exe SSH client as it is standalone, has a GUI so you can see it pop up and you can then close it and cuckoo terminates soon after so it is a good test. One it is done running check the web interface for the report, behaviour logs etc.

That is basically the flow of things so if you kind of go with that, follow the documentation stages and resolve each issue you will get there.

**Comment by Monkie1990** [comment]
Thanks @kevross33!
