### ISSUE TITLE
Changes to behavioral analysis summary

### ISSUE THREAD

**Issue by jgajek** [spender-sandbox/cuckoo-modified#295]
I am considering reworking the behavioral analysis summary in the web interface to break down the observed activity by process -- when the analysis involves multiple processes, it is useful to know which process did what at a glance without wading through the detailed API log.  Perhaps include a few additional types of activity (atoms, web calls, socket calls).

Is this something that would be accepted here?  I'm not looking to maintain a separate fork.

**Comment by spender-sandbox** [comment]
Add it in a separate tab

-Brad
