### ISSUE TITLE
clamav warnings

### ISSUE THREAD

**Issue by lehuff** [spender-sandbox/cuckoo-modified#304]
I think clamav is being detected incorrectly.  Consistently getting the following error message:

2016-09-27 09:17:50,053 [lib.cuckoo.common.objects] WARNING: failed to scan file with clamav Error 2 connecting /var/run/clamav/clamd.ctl. No such file or directory.

Tried this on multiple installs (mostly on CentOS) and get the same results. ClamAV is not installed (don't want it).  Maybe pull the check to a config file so it can be disabled and not run the scan?

**Comment by spender-sandbox** [comment]
pip uninstall clamd

-Brad

**Comment by lehuff** [comment]
derp!
