### ISSUE TITLE
Standalone Sandbox?

### ISSUE THREAD

**Issue by Monkie1990** [spender-sandbox/cuckoo-modified#308]
Is it possible to run cuckoo-modified on two separate VMs? ie, have ubuntu (which will be a VM) run cuckoo but instead of having a windows sandbox within ubuntu, have the windows sandbox as a separate VM as well. 

I was looking at physical.conf file but not sure if thats what I need to use to make this work.

Thanks!

**Comment by hexlax** [comment]
Yes - you would use a physical machine set up and have your VM manager revert to snapshot on shutdown. 

More info:
http://docs.cuckoosandbox.org/en/latest/installation/guest_physical/saving/#setup-using-vmware-bonus

**Comment by Monkie1990** [comment]
Thanks!
I'm having trouble with the network configuration (trying to get the ubuntu act like a gateway so I can inetsim to work properly) ........ I found this tutorial (http://www.adeptus-mechanicus.com/codex/hcvmu/hcvmu.php) but not sure if this is appropriate for what I need .... any thoughts?
