### ISSUE TITLE
How to submit PE with sideloaded DLL?

### ISSUE THREAD

**Issue by marcurdy** [spender-sandbox/cuckoo-modified#309]
I don't see any way to submit multiple files to cuckoo such that the payload only executes when multiple files are colocated at pe execution.  Zip's always unarchive before a file is shipped to the VM.  Is this a thing with cuckoo?

**Comment by spender-sandbox** [comment]
Specify the zip package, it won't get auto-extracted then.  You can do this too with a zip file containing a batch script and any other files, then specify in the options for the batch script to be executed.

-Brad
