### ISSUE TITLE
Be Able To Provide Password To Protected Word Docs

### ISSUE THREAD

**Issue by eoinmiller-sfdc** [spender-sandbox/cuckoo-modified#312]
Would it be possible to add functionality to provide a password to password protected word docs? I noticed this is possible to be passed for zip archives. I don't know if the title of this window could be monitored for and then the submitted cuckoo switch value provided:

![image](https://cloud.githubusercontent.com/assets/15840028/19044588/fa1fb71e-8962-11e6-8724-a8368d18db74.png)

**Comment by spender-sandbox** [comment]
It would be possible, though I'd rather the documents just be decrypted/rewritten in the demux code rather than in the guest, otherwise we'll miss out on static analysis (as oletools itself doesn't support handling it)

-Brad

**Comment by eoinmiller-sfdc** [comment]
That makes entirely too much sense! Suggestion withdrawn.

**Comment by jgajek** [comment]
@spender-sandbox So perhaps we can have the msoffice packages call a compiled version of this?

https://github.com/herumi/msoffice

**Comment by spender-sandbox** [comment]
Yep, exactly

-Brad

**Comment by jgajek** [comment]
OK to add a config option in auxiliary.conf to point to the msoffice decryption binary?  If the binary is not found, or there is an error in decrypting the document file, the demux code will just return the unaltered file.

**Comment by spender-sandbox** [comment]
Sounds good

**Comment by irishhuggiebear** [comment]
Hi all,

Sorry if i am behind in the conversation. So if i was running Cuckoo to analyize a password protected document, is there a way of passing the password too the document in a sandbox environment like cuckoo? thanks Huggie

**Comment by spender-sandbox** [comment]
With the current code, just add password=thepassword in the options field on the submit page.

-Brad

**Comment by jgajek** [comment]
@irishhuggiebear What Brad said.  You will need to compile the msoffice-crypt.exe binary from https://github.com/herumi/msoffice on your Cuckoo box and specify the path to it in auxiliary.conf.

**Comment by irishhuggiebear** [comment]
Ok thanks Brad & thanks @jgajek much appreciated.

**Comment by zashraf1337** [comment]
we can also integrate this https://github.com/nolze/ms-offcrypto-tool

**Comment by doomedraven** [comment]
That already integrates but withanothwr tool which you need to compile and put in data
