### ISSUE TITLE
global name 'es_as_db' is not defined

### ISSUE THREAD

**Issue by agaglia** [spender-sandbox/cuckoo-modified#318]
Hi, we have configured the latest version of cuckoo-modified yesterday. Browsing the report of the analysis we realized that the "Compare to the analysis ..." shows an error concerning Elasticsearch, but we have configured Mongodb only. Following the report of the error:

_global name 'es_as_db' is not defined
Request Method:
GET 

Request URL:
http://xxxx.xxxxx.xxxxx/compare/24/ 

Django Version:
1.10.2 

Exception Type:
NameError 

Exception Value:
global name 'es_as_db' is not defined
 

Exception Location:
/home/socadmin/cuckoo-modified/web/compare/views.py in left, line 84 

Python Executable:
/usr/bin/python 

Python Version:
2.7.6 

Python Path:
['/home/socadmin/cuckoo-modified/web',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/local/lib/python2.7/dist-packages/PyV8-1.0_dev-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/pefile-2016.3.28-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/pefile2-1.2.11-py2.7.egg',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/pymodules/python2.7',
 '/home/socadmin/cuckoo-modified/web/..',
 '/home/socadmin/cuckoo-modified/web/..',
 '/home/socadmin/cuckoo-modified/web/..',
 '/home/socadmin/cuckoo-modified/web/..',
 '/home/socadmin/cuckoo-modified/web/..',
 '/home/socadmin/cuckoo-modified/web/..',
 '/home/socadmin/cuckoo-modified',
 '/home/socadmin/cuckoo-modified/web',
 '/home/socadmin/cuckoo-modified/web/..']_
 
THX

**Comment by doomedraven** [comment]
try this:

in line 16
`/home/socadmin/cuckoo-modified/web/compare/views.py`
add 
`es_as_db = False'

**Comment by agaglia** [comment]
It Works!!
Thx!!
