### ISSUE TITLE
Type Error in `views.py`

### ISSUE THREAD

**Issue by geudrik** [spender-sandbox/cuckoo-modified#32]
I ran across this issue a while back, not sure the issue made the transition with you. 

https://github.com/brad-accuvant/cuckoo-modified/commit/3fa0dafe15e0c5a4472a60c4a54923df4523e77d

<img width="604" alt="screen shot 2016-02-01 at 4 30 46 pm" src="https://cloud.githubusercontent.com/assets/2020115/12732059/ca4d4690-c901-11e5-9829-235ee079dd08.png">

The `fix` I proposed shouldn't be utilized as such, but it prevents the issue as a stop-gap. Thoughts as to why this might be happening?

**Comment by spender-sandbox** [comment]
started_on is a nullable field in in the Task column, so your fix is probably correct.  If the server was shut down or encountered an error at some point in between a task being pending and running, then it might be left as None

-Brad

**Comment by geudrik** [comment]
Ahh, alright I'm tracking. I'll run a query locally and see what I can dredge up. 

I'll get a PR for you here shortly.

Cheers, Brad!
