### ISSUE TITLE
Warning - Failed to find usable Suricata log file

### ISSUE THREAD

**Issue by Antelox** [spender-sandbox/cuckoo-modified#320]
Hi to all!
Any hints about this error? I got it at every analysis launched. I tried with different Suricata version, but same problem.

[modules.processing.suricata] WARNING: Suricata: Failed to find usable Suricata log file

Tnx in advance.

**Comment by doomedraven** [comment]
did you have activated eve log?
* check how to configure suricata https://infosecspeakeasy.org/t/howto-build-a-cuckoo-sandbox/27 to verify what you have the same config

```
       datalist = []
        if os.path.exists(SURICATA_EVE_LOG_FULL_PATH):
            suricata["eve_log_full_path"] = SURICATA_EVE_LOG_FULL_PATH
            with open(SURICATA_EVE_LOG_FULL_PATH, "rb") as eve_log:
                datalist.append(eve_log.read())
        else:
            for path in separate_log_paths:
                if os.path.exists(path[1]):
                    suricata[path[0]] = path[1]
                    with open(path[1], "rb") as the_log:
                        datalist.append(the_log.read())

        if not datalist:
            log.warning("Suricata: Failed to find usable Suricata log file")

```

**Comment by Antelox** [comment]
Hi doomedraven, thanks for your reply! Anyway I had already checked the tutorial. In fact the problem is about the config file derived from _suricata-debian.yaml_. In that file there is not **eve-log** field option so I got the issue. I solved now deriving suricata config for cuckoo from _suricata.yaml_ instead and works fine without that warning.
The problem now is that I don't get any hits on the report about suricata rules. Suricata config seems to be not the problem because I tried by hand with a pcap downloaded from hybrid-analysis sandbox (darkcomet sample) and it's ok.
I done: suricata -c /etc/suricata/suricata-cuckoo.yaml -k none -r network.pcap

Do you have any sample with which I can make any tests through cuckoo and that some emerging threats rules are triggered?

Thanks in advance! =)

**Comment by doomedraven** [comment]
try this one:
* f5c7bbe0ecab3429f1cc6d8066e1db2d

should match a lot of: 
* ET DNS Query to a *.pw domain - Likely Hostile

**Comment by marek2003** [comment]
Download some pcaps and see if suricata works properly.
http://www.malware-traffic-analysis.net

**Comment by marek2003** [comment]
http://www.malware-traffic-analysis.net/training-exercises.html
Obviously submit as pcap  and not as file of not cuckoo won't works.

**Comment by Antelox** [comment]
@doomedraven with your sample, rules hit correctly as you said! So I think now it's definitely ok otherwise I will write again! :P
@marek2003 thanks you too for the your replies/hints

**Comment by Antelox** [comment]
Can be closed! :)
