### ISSUE TITLE
Submit a particular file makes django to raise error 500

### ISSUE THREAD

**Issue by marek2003** [spender-sandbox/cuckoo-modified#333]
Hi all,
I submitted this file to my cuckoo : https://malwr.com/analysis/Nzk4NTlkZTc3ZmRhNGM4Y2I3NWMzNzUwMTQ0MGRhNzY/
It's a zip with 2 files inside: a .VBE and an .SCR. both processing went ok but, if I go into the  SCR(IMG001.scr) report I get error 500. NO problem at all if I check  "No Injection (disable behavioral analysis)" on submit page.
I would like to know if anyone else experienced this behaviour.
thanks in advance
M.

**Comment by doomedraven** [comment]
see/post logs from console

**Comment by marek2003** [comment]
I enabled debug in local_settings.py and I got this:
'utf8' codec can't decode bytes in position 198-199: invalid continuation byte. You passed in 'C:\\Windows\\system32\\cmd.exe  /S /D /c" @ xcopy /y /d "C:\\Users\\Seven01\\AppData\\Roaming\\NsMiner\\IMG001.exe" "\\\\192.168.56.1\\C$\\Documents and Settings\\1\\\xef\xbf\x83\xef\xbf\xab\xef\xbf\xa0\xef\xbf\xa2\xef\xbf\xad\xef\xbf\xae\xef\xbf\xa5 \xef\xbf\xac\xef\xbf\xa5\xef\xbf\xad\xef\xbf\xbe\\\xef\xbf\x8f\xef\xbf\xb0\xef\xbf\xae\xef\xbf\xa3\xef\xbf ...(truncated)' (<type 'str'>)

**Comment by spender-sandbox** [comment]
Thanks, I'll look into this.

-Brad

**Comment by spender-sandbox** [comment]
Can you try the latest version?  It should be fixed now.

-Brad

**Comment by marek2003** [comment]
it works !!!!!! thanks a lot @spender-sandbox
