### ISSUE TITLE
No pcap for some analyses using KVM

### ISSUE THREAD

**Issue by patrika** [spender-sandbox/cuckoo-modified#347]
Noticed that some analyses did not have a PCAP even due I submitted an URL and saw in the pictures that the page was displayed by the browser. So I looked into it..

--Tailing log/Cuckoo.log:
...
2016-11-04 15:02:06,893 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 47717 (interface=vnet2, host=192.168.100.134, dump path=/opt/cuckoomodified/storage/analyses/1158/dump.pcap)
...

--conf/kvm.conf:
...
[cuckoo-off4]

label = cuckoo-off4
platform = windows
ip = 192.168.100.134
...

--Python instance:
 > time.ctime(time.time())
'Fri Nov  4 15:01:55 2016'
 >ET.fromstring(libvirt.openReadOnly(None).lookupByName("cuckoo-off4").XMLDesc()).find("./devices/interface[@type='network']").find("target").attrib["dev"]
'vnet4'
 >time.ctime(time.time()) 
'Fri Nov  4 15:02:14 2016'

As you can see the interface differs between the running domain in KVM ("vnet4") and the entry in the database("vnet2") and I guess the issue is here:

--modules/machinery/kvm.py
`29:     if not self.db.view_machine_by_label(label).interface:`

Where the interface is NOT updated since there is already an entry for it in the DB.

I have not checked, but I guess that KVM uses the first available vnet interface(incrementally or similar) and if you use multiple KVM guests and run them out of order there will be a mismatch. Probably if you update the interface each time the guest starts there will be no issue.

**Comment by spender-sandbox** [comment]
I don't think you're supposed to be sniffing on the vnet* interfaces, afaik they can be shared among multiple VMs.

-Brad

**Comment by doomedraven** [comment]
you can specify interface per vm, so you can put all the same for all of them, I have specified it and never had problem with pcaps and kvm

**Comment by patrika** [comment]
Hum I thought that you wanted to use the vnet* interfaces since those are only active during the uptime of the guest...

**Comment by doomedraven** [comment]
i have my kvm interface activated all the time, as it shared between vms, not even cuckoo's vms

**Comment by patrika** [comment]
Yeah I understand that I could hard code the interface in the kvm.conf for each guest ,to example virbr0. But if you use that technique it is still the same issue, as brad mentioned, with multiple VMs using the same interface.

**Comment by doomedraven** [comment]
never had issue with this

**Comment by patrika** [comment]
Anyway a hotfix for this would be to comment out:
line 29 in --modules/machinery/kvm.py:
`#if not self.db.view_machine_by_label(label).interface:`

**Comment by spender-sandbox** [comment]
I think that's why you need to specify separate interfaces for each VM of the virbr* variety.

**Comment by KillerInstinct** [comment]
I sniff the virbr* in my kvm setup.
