### ISSUE TITLE
Behavior API Search Box Broken?

### ISSUE THREAD

**Issue by keithjjones** [spender-sandbox/cuckoo-modified#348]
The right most box in the behavior that says "Comma Separated API Filter" does not seem to work no matter what I put into it and press enter.  The page does not change.

**Comment by KillerInstinct** [comment]
Put the filter in (without spaces) and then click any of the API 'buttons'. It's not enter key-entry, it's applied to a search using the buttons themselves.

**Comment by keithjjones** [comment]
Sweet, thanks @KillerInstinct!
