### ISSUE TITLE
MongoDB Module Error

### ISSUE THREAD

**Issue by Ciriio** [spender-sandbox/cuckoo-modified#354]
When analyzing a windows script file document, I receive the following error message regarding the MongoDB module:

```
2016-11-10 11:39:45,122 [lib.cuckoo.core.plugins] DEBUG: Executing reporting module "MongoDB"
2016-11-10 11:39:57,431 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/cuckoo/utils/../lib/cuckoo/core/plugins.py", line 629, in process
    current.run(self.results)
  File "/cuckoo/utils/../modules/reporting/mongodb.py", line 185, in run
    child_key, csize = self.debug_dict_size(report[parent_key])[0]
  File "/cuckoo/utils/../modules/reporting/mongodb.py", line 46, in debug_dict_size
    totals = dict((k, 0) for k in dct)
TypeError: unhashable type: 'dict'
```

Link to my wsf document: https://mega.nz/#!o1QACahb!EDK4bjpeOeUkOSqa--GUQjB-qXKAFU6S0rmV4qWAoxU (password: infected)
e: Same issue with this PE file: https://mega.nz/#!M1RlnB7b!l1ooHvJ4PmrHd03yMQNQ4tmvtJhamsahEwKRK6BliJI (password: infected)

e: Similar Issue? https://github.com/spender-sandbox/cuckoo-modified/issues/196 (I am running pefile2=1.2.11)

I am able to reproduce this issue on fresh installations (on my Ubuntu 14.04 machine). Is there any way I can debug this issue?
The report.json file is being created but the web frontend is not showing any report because the data has not been written in MongoDB. I am currently using ElasticSearchDB as workaround.

Thank you in advance.

**Comment by spender-sandbox** [comment]
Did it end up being a pefile issue? Only other time I've seen this is someone who writes a signature incorrectly doing self.data.append({blah, blah2}) instead of self.data.append({blah : blah2})

-Brad

**Comment by Ciriio** [comment]
Close guess, it was an error on my end. A yara rule which I kept automatically adding to new setups was faulty.
