### ISSUE TITLE
"ERROR :-( Error adding task to Cuckoo's database."

### ISSUE THREAD

**Issue by hemzaz** [spender-sandbox/cuckoo-modified#36]
Hi!
I am using latest cuckoo-modified from spender-sandbox.
I have here A new cuckoo installation with vbox and all the dependencies.
For some reason i get the following error when i try to submit samples on the web dashboard
via /submit/ page.
the issue occurs when trying to submit sample for analysis quarantine file or trying to analyse some URLs.
i added some screenshots to demonstrate the issue.
--elad

![cuckoo1](https://cloud.githubusercontent.com/assets/1830915/12809384/6edb0bd4-cad3-11e5-8292-41419134e806.PNG)
![cuckoo2](https://cloud.githubusercontent.com/assets/1830915/12809390/78305806-cad3-11e5-89fc-c5978d99fee2.PNG)

**Comment by spender-sandbox** [comment]
There should be some error printed in the console you started cuckoo.py from.  Probably you need to upgrade the database schema.

-Brad

**Comment by KillerInstinct** [comment]
The error may also be a traceback in manage.py, depending on how you setup your web interface.

**Comment by hemzaz** [comment]
thanks!

@spender-sandbox 
as far as i can see there are no errors on the cuckoo.py console, 
i also started cuckoo with -d flag to activate debug mode. 
and how do i upgrade the db schema?

@KillerInstinct 
can you elaborate on it?
as i started to dig into views.py without any success

so much thanks for the help!
--elad

**Comment by KillerInstinct** [comment]
Run django using ./manage.py runserver 0.0.0.0:8080 and submit it to that webserver. It should pop up with an error on the console that the wevserver is running on.

**Comment by hemzaz** [comment]
Hi @KillerInstinct 
currently i run cuckoo.py on port 8080
and manage.py on port 8000
--elad

**Comment by KillerInstinct** [comment]
Port doesn't really matter in this case, just have your manage.py console open and submit a task. Then see what the error is from manage.py -- thats where it should pop up.

**Comment by hemzaz** [comment]
Hi All!
The issue solved,
as it seems the culprit was sqlite3
i switched to mysql and whoaa it works.
great thanks for the help with this issue
you helped me allot with narrowing down the reasons for the symptom.
--elad
