### ISSUE TITLE
exclude behavioral data in the JSON response

### ISSUE THREAD

**Issue by marek2003** [spender-sandbox/cuckoo-modified#363]
Hi All,
is there any way on jsondump.py to choose if exclude or not the  behavioral data? If I submit a PE like a Ransom 500 MB of Json is created making it impossible to parse.
thanks in advance
M.

**Comment by housemusic42** [comment]
absolutely. write a custom reporting module and stick it under $CUCKOO_HOME/modules/reporting and then add it to your configs. 

here's an example one i'm pulling info, target, malscore and vt

```
import os
import json
import codecs

from lib.cuckoo.common.abstracts import Report
from lib.cuckoo.common.exceptions import CuckooReportError

class JsonDump(Report):
    """Saves analysis results in JSON format."""

    def run(self, results):
        """Writes report.
        @param results: Cuckoo results dict.
        @raise CuckooReportError: if fails to write report.
        """
        try:
            report = codecs.open(os.path.join(self.reports_path, "report.json"), "w", "utf-8")
            wanted_keys = ['info', 'target', 'malscore', 'virustotal']
            wanted_dict = { wanted_key: results[wanted_key] for wanted_key in wanted_keys }
            json.dump(wanted_dict, report, sort_keys=False, indent=4)
            report.close()
        except (UnicodeError, TypeError, IOError) as e:
            raise CuckooReportError("Failed to generate JSON report: %s" % e)
```

**Comment by spender-sandbox** [comment]
I'd be open to a config option for the jsondump module that eliminates behavioral calls from the output -- in most of my uses of it at least, I've never needed to look at specific calls.

-Brad

**Comment by jgajek** [comment]
As long as it's optional -- I routinely look at the API call logs.

**Comment by marek2003** [comment]
it works!!!!!!!! thanks @housemusic42 !!
