### ISSUE TITLE
Yararules Online

### ISSUE THREAD

**Issue by marek2003** [spender-sandbox/cuckoo-modified#365]
There's a new online service of yara Rule scanning (https://analysis.yararules.com/)
If they have  api services  it would be a very nice  integration with cuckoo (like VT).

**Comment by KillerInstinct** [comment]
We already have yara support -- it would make more sense to just use the rules you wanted in your own cuckoo rig. If they're vetted with little-to-no false positives, (and licensing allows) they should be added to the repo in data/yara/

**Comment by marek2003** [comment]
yep, u're right . My idea was just to have a "second voice" to see if some yara rules are missing on data/yara. Infact after a submission there are a direct link to the repo for each signature that are matched.
