### ISSUE TITLE
digital signature on static analysis 

### ISSUE THREAD

**Issue by marek2003** [spender-sandbox/cuckoo-modified#372]
hi all ,maybe I'm wrong but  I've noticed that, analyzing an executable with digital signature, the report shows only the personal certificate (not the full path with intermediate and CA) and, it doesen't never show if the file has a "counter signature" (dunno if it's right in english). 
Do you think this is a limitation of Pefile? 
the MD5 is: 37cfb7e529cc77dac0edb6b2842556b9
https://www.reverse.it/sample/1fc4091cd15ac5f632b4d199c1877b00dd3b7c751a4e64b81e111d413236b85c?environmentId=100
Thanks to all for the support

**Comment by KillerInstinct** [comment]
Is this the digital cert information from pefile or the one from the VM using signtool?

**Comment by marek2003** [comment]
dunno if understood (forgive my bad english). On the cuckoo web report i get the personal cert (PPLive Corporation 5e96a8eca88cd9d81e6e13b89a3178eb) while, simply using the windows property tab or Pestudio  I get the cert and the counter signature .

**Comment by marek2003** [comment]
@KillerInstinct  am i doing right? do you have any suggestion?
regards
