### ISSUE TITLE
Django Not being rendered for cuckoo web ui

### ISSUE THREAD

**Issue by Monkie1990** [spender-sandbox/cuckoo-modified#373]
When I try to load the cuckoo web ui I see that Django is not being rendered..... according to the error.log "/opt/cuckoo/web/web/{{ STATIC_URL }}graphic/cuckoo.png" does not exist (STATIC_URL is /static/)....... but when I check the filesystem the file does indeed exists .... I'm not sure why there is an error, but any insite is greatly appreciated.

**Comment by doomedraven** [comment]
Provide how you started webgui, and how you try access ir, also software versions

**Comment by Monkie1990** [comment]
I have no GUI on the to the web server so Im accessing it via an external IP on port 8000 .... Im using nginx 1.10.0

I also run sudo /usr/sbin/cuckooboot in the background,.... here's a screen shot of what it looks like with out the fancy stuff


![image](https://cloud.githubusercontent.com/assets/21345323/20540339/e6b2bd3a-b0c6-11e6-9a09-eed3b878324c.png)

**Comment by doomedraven** [comment]
Looks like incorrect nginx config

Best regards
Andriy

**Comment by Monkie1990** [comment]
It turned out I was accessing the WebUI from the wrong ports.... Greatly appreciate your feedback!
