### ISSUE TITLE
No screenshots

### ISSUE THREAD

**Issue by gokumatrix** [spender-sandbox/cuckoo-modified#374]
I apologize if this is written somewhere but I looked around in the issues/readme and couldn't find anything.

Cuckoo runs perfectly except it will not take screenshots. Do I need to move screenshots.py to the guest VM or something, or is there a setting in a .conf I missed to turn it on? I tried running it with --debug but I didn't see an error saying it was trying to take them and couldn't. I have pillow installed on my Windows machine as well. If I can provide more information to help diagnose what's going on, just let me know.

Thank you!

**Comment by spender-sandbox** [comment]
Did you install PIL in the guest VM?

-Brad

**Comment by doomedraven** [comment]
i responded to this question in your issue in cuckoo upstream

**Comment by gokumatrix** [comment]
I have pillow, not PIL. I understood that pillow was the updated version.
@doomedraven - I accidentally posted it there but my issue is with this modified version. I thought that may be part of the issue.

**Comment by doomedraven** [comment]
then close it there, and why you not installed it when i pointed you to the problem? install correct library

**Comment by spender-sandbox** [comment]
Check the analysis.log, is there a message there saying:
Python Image Library is not installed, screenshots are disabled ?

**Comment by gokumatrix** [comment]
@doomedraven I was waiting for your response on whether pillow was okay to be installed, being it was an updated version of PIL as I understood. I didn't realize they could be installed side by side, so I'll install that now.
@spender-sandbox I don't see an analysis.log. The only log I see is cuckoo.log, but that doesn't give any error that you mentioned

**Comment by jgajek** [comment]
@gokumatrix Yes, pillow should work just fine instead of PIL.

**Comment by gokumatrix** [comment]
In that case, it's already installed. I'll still install PIL just in case, but if pillow is okay, then is there a setting I'm missing? Through browsing these threads I wasn't able to find a setting to enable screenshots. It read like they were just enabled by default

**Comment by spender-sandbox** [comment]
The analysis.log is viewable via the web interface, right at the top of the summary report.  It's also in storage/analyses/*/analysis.log

**Comment by gokumatrix** [comment]
@doomedraven sorry for doubting you! I installed PIL and now everything works as intended. pillow was also installed, but screenshots did not work. @spender-sandbox thanks for the heads up about the log.

**Comment by keithjjones** [comment]
That's odd, I've only ever installed pillow and it works.

**Comment by KillerInstinct** [comment]
same, Pillow works fine here as well.

**Comment by doomedraven** [comment]
@gokumatrix i glad what error is solved :)
btw can you tell us which version of pillow did you install before ? as it can be the problem, as we saw with peframe

**Comment by doomedraven** [comment]
also `being it was an updated version of PIL as I understood`, yah it is :) but this stuff happens, i have installed pillow, but in some vms i had problems in past, but have template vm solve everything :)

**Comment by doomedraven** [comment]
@gokumatrix btw as it solved, probably you can close it ;)
