### ISSUE TITLE
Add to whitelist?

### ISSUE THREAD

**Issue by gokumatrix** [spender-sandbox/cuckoo-modified#382]
Apologies if this is in the wrong spot. I didn't see a question section, and looked through the issues and some of the code but I didn't see anything about this.

Is there a way to add the results of an analysis to a whitelist? So I run a blank Microsoft Word document through cuckoo and it comes up with X DNS requests, files modified, etc. Could I then say "take this analysis and add everything (URL, IP, registry keys read, etc) to a whitelist"

Thank you!

**Comment by spender-sandbox** [comment]
There is currently no way of doing that.

-Brad

**Comment by gokumatrix** [comment]
okay, thank you!
