### ISSUE TITLE
cuckoomx by doomedraven

### ISSUE THREAD

**Issue by marek2003** [spender-sandbox/cuckoo-modified#386]
@doomedraven  do you think  is it possible to apply an official PR on cuckoomod like you did on cuckoosandbox? (https://github.com/cuckoosandbox/cuckoo/pull/1175) 
The idea of receiving/analyzing the sample by mail was an old dismissed project  but it can be very useful 
kind regards
M.

**Comment by doomedraven** [comment]
it works on cuckoo-mod, i have deployed it, just download and start it, i not used demux func to unpack archives, as v2 don't have it, is why I used sflock

feel free to get it, change sflock to demux and pr it here

**Comment by marek2003** [comment]
tks as always!
regards
M.
