### ISSUE TITLE
Exception in thread Thread-1: Traceback (most recent call last):   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner     self.run()   File "dist.py", line 748, in run     self.submit_tasks(node, MINIMUMQUEUE[node.name] - status["pending"]) KeyError: u'master'

### ISSUE THREAD

**Issue by gqqcode** [spender-sandbox/cuckoo-modified#387]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "dist.py", line 748, in run
    self.submit_tasks(node, MINIMUMQUEUE[node.name] - status["pending"])
KeyError: u'master'

**Comment by doomedraven** [comment]
you not configured properly your setup

**Comment by gqqcode** [comment]
@Thank you for your help, I try again, I hope you can quickly update the document

**Comment by doomedraven** [comment]
it done alrady

**Comment by gqqcode** [comment]
@doomedraven ok，thank you

**Comment by gqqcode** [comment]
@doomedraven I use Cuckoo Sandbox 2.0-rc2 and configured [distributed], but the same error, I need to modify other things? Is not dist.py can not be used in Cuckoo Sandbox 2.0-rc2?

**Comment by spender-sandbox** [comment]
Wrong repo for this question.

-Brad

**Comment by doomedraven** [comment]
RTD https://github.com/spender-sandbox/cuckoo-modified/blob/master/docs/book/src/usage/dist.rst#quick-usage

looks like you not even readed it
