### ISSUE TITLE
Type exceptions Memory Error

### ISSUE THREAD

**Issue by shaahint** [spender-sandbox/cuckoo-modified#39]
Hi,
I'm using cuckoo sandbox version 2.0, it works well but when I want to analyze a large file (e.g 85 MB), an error occurs : unable to upload malware to analysis machine (type exceptions Memory Error)
Although I changed the upload-max-size and analysis-size-limit in the file cuckoo.conf, an error still occurs

Extra information:
Host: Ubuntu version 14.04 (run on ESX)
Python version 2.7
Guest: Windows7 32 bit
Any suggestion please?
Thanks,
Shaahin.

**Comment by spender-sandbox** [comment]
If you're using the upstream 2.0 version, you should report it at https://github.com/cuckoosandbox/cuckoo instead.

-Brad
