### ISSUE TITLE
Unable to add wildcard to URL whitelist / does .bup extension work?

### ISSUE THREAD

**Issue by gokumatrix** [spender-sandbox/cuckoo-modified#390]
I'm attempting to create a whitelist for cuckoo and I believe it needs to be done in /modules/processing/network.py in this area:

``self.domain_whitelist = [
            "^ocsp\.usertrust\.com$",
            "^ocsp\.comodoca\.com$",
            "^ctldl\.windowsupdate\.com$",
            "^crl\.microsoft\.com$",
            "^ieonline\.microsoft\.com$"``

but I can't figure out how to add a wildcard. I tried, "*.domain.com" but that didn't work. I was able to get a URL whitelisted by writing in the exact string of the site being targeted. Am I in the right file for this? Am I supposed to be using a different syntax? If I want to whitelist an IP address is this the same place I'd go?

Additionally, in lib/cuckoo/common/quarantine.py I read the code and it seems that cuckoo would accept .bup files. I didn't find any documentation about it other than in this code, but if it can is there something specific I need to do in order to enable it, or do I just need 7zip and xor.exe on the Windows box?

I appreciate any help you can provide!

**Comment by KillerInstinct** [comment]
1) What data/fields are you attempting to whitelist? From the hosts/ip on the main analysis page? 
2) .bup extraction should work automatically if you submit the quarantine file to the quarantine file submission tab (in Submit there should be File/Quarantine File/URL/etc)

**Comment by gokumatrix** [comment]
1) Yes, from the hosts/ip area on the main analysis page

2) It has come to my attention that I am an idiot and didn't submit it through the quarantine section, but through the normal file section. Thanks, that worked.

**Comment by KillerInstinct** [comment]
Cool, number 2 is an easy one then.

As for domain whitelisting, make sure you have the option enabled here:
https://github.com/spender-sandbox/cuckoo-modified/blob/master/conf/processing.conf#L36

It's disabled by default as it would break some peoples rigs. There's a comment above the option explaining why. It should also be noted that wildcards on regex are ```.*``` and not just ```*``` so your regex would be ```.*\.domain\.com``` (Preferably anchored with a $ if you know .com is the end of the domain)

For IP's you can just add your IP's as strings to self.ip_whitelist here:
https://github.com/spender-sandbox/cuckoo-modified/blob/master/modules/processing/network.py#L103

It could be changed to something like:
```
self.ip_whitelist = set([
    "1.2.3.4",
    "5.6.7.8",
])
```

**Comment by gokumatrix** [comment]
So the literal line I have (including double quotes) is:
".*\.bing\.com$"

as a test.  I verified whitelist is on, but when I run this I still get api.bing.com and c.bing.com in my results.

**Comment by KillerInstinct** [comment]
And you've restarted cuckoo.py or process.py?

Cause in IDLE it seems to work fine:
```
import re
>>> print re.match(".*\.bing\.com$", "api.bing.com")
<_sre.SRE_Match object at 0x02A722C0>
>>> print re.match(".*\.bing\.com$", "c.bing.com")
<_sre.SRE_Match object at 0x02A722C0>
```

**Comment by gokumatrix** [comment]
I had restarted cuckoo.py and it didn't work. I just rebooted the machine though and it worked perfectly! Not sure what happened, but just verified it with 2 website submissions and everything is golden. Thanks for the help!
