### ISSUE TITLE
VB2016 paper: Defeating sandbox evasion: how to increase successful emulation rate in your virtualized environment

### ISSUE THREAD

**Issue by hexadite-lior** [spender-sandbox/cuckoo-modified#391]
https://www.virusbulletin.com/blog/2016/december/vb2016-paper-defeating-sandbox-evasion-how-increase-successful-emulation-rate-your-virtualized-environment/

https://www.virusbulletin.com/virusbulletin/2016/12/vb2016-paper-defeating-sandbox-evasion-how-increase-successful-emulation-rate-your-virtual-environment/

https://github.com/checkpointsw/vb2016-sandbox-evasion

**Comment by spender-sandbox** [comment]
Already aware of it -- you can see my comment on their github.  I don't think it has anything to do with increasing successful emulation rate though ;)

-Brad

**Comment by hexadite-lior** [comment]
That was quick :)
Thanks!
