### ISSUE TITLE
UnicodeEncodeError: (solved) 

### ISSUE THREAD

**Issue by Nwinternights** [spender-sandbox/cuckoo-modified#393]
Hi,
the scheduler.py rais an ecception if i try submit particular files with special characters(es I  ⭐️ bla bla)
the error is: 'ascii' codec can't encode characters in position xxxx : ordinal not in range(128)
by the way i solved  adding the following lines on scheduler.py :

# -*- coding: utf-8 -*- 

and

import sys
reload(sys)
sys.setdefaultencoding('utf8')

I'm sure that this is not the cleanest way to solve the problem :-)
regards

**Comment by Nwinternights** [comment]
in the same way i solved the human.py in case of special characters in  the dictionary (italian for example)
https://github.com/spender-sandbox/cuckoo-modified/issues/381

**Comment by spender-sandbox** [comment]
Known issue, though a proper fix requires us to preserve the unicode filename through the entire execution (to the analyzer and cuckoomon).

-Brad

**Comment by Nwinternights** [comment]
tks Brad for the quick answer and well, I guess I can close the thread.
regards
Marco
