### ISSUE TITLE
Rest Api document must  be updated

### ISSUE THREAD

**Issue by kenanbirkan** [spender-sandbox/cuckoo-modified#395]
Rest api document at link;
https://github.com/spender-sandbox/cuckoo-modified/blob/master/docs/book/src/usage/api.rst

must be updated for /tasks/create/file
example says ;
json_decoder = json.JSONDecoder()
task_id = json_decoder.decode(request.text)["task_id"]

but code at link ;
https://github.com/spender-sandbox/cuckoo-modified/blob/master/utils/api.py

returns 
response["task_ids"] = task_ids

**Comment by doomedraven** [comment]
feel free to push changes yourself next time ;)

**Comment by kenanbirkan** [comment]
Ok, I've updated :)
