### ISSUE TITLE
Having issues with processing modules

### ISSUE THREAD

**Issue by benrau87** [spender-sandbox/cuckoo-modified#401]
Hello,
Running a new setup of cuckoo and processing was never completing. Try running under debug and turned off the modules one by one as they hung. Now processing just fails altogether, but decompression, behavior, network, and static modules still run.
Any ideas where this could be stemming from?
Thanks!

**Comment by spender-sandbox** [comment]
Need more info, not much to go on from what you've written so far.

-Brad

**Comment by benrau87** [comment]
Hey Brad,

What would be appropriate? The debug output from the processing module?

**Comment by spender-sandbox** [comment]
Sure, that'd help, also what kind of file you were trying to analyze.

-Brad

**Comment by benrau87** [comment]
Just doing a test run to make sure everything was working with a legit exe of 7zip. Always worked in the past, the only change is that I moved to mysql database for this deployment. I'll get the output once I fire that sample off again.

**Comment by benrau87** [comment]
After sometime looking at the initial configuration, I figured out the issue. I used vmcloak to create my machines and forgot to kill the included agent. The issues all stemmed from having two agents running on the machines.
Thank you for your quick replies Brad!
