### ISSUE TITLE
ERROR: Analysis failed: invalid string pointer 0x03981A5000000000

### ISSUE THREAD

**Issue by william-second** [spender-sandbox/cuckoo-modified#405]
Hi all, 
I run this modified version of cuckoo and encountered with the above error. Any suggestion to solve it? 
Thanks,

**Comment by doomedraven** [comment]
Do you use x64 bit python? I think i saw that on issues with x64 python

**Comment by william-second** [comment]
yes, I uses x64 python (ubuntu 16.04 LTS). Should I install x32 python then retry? 
Thanks .

**Comment by doomedraven** [comment]
see this https://github.com/spender-sandbox/cuckoo-modified/issues/351 for answer

**Comment by william-second** [comment]
thanks. It works now. BTW, do you know where I can find the results of Malheur after the analysis terminates?

**Comment by doomedraven** [comment]
if you have properly configured it, you should see tab "similar" or something like that i don't remember exact name on webgui inside of analysis, as resolved original issue, close it ;)
