### ISSUE TITLE
Administrative question - Processing Jobs

### ISSUE THREAD

**Issue by housemusic42** [spender-sandbox/cuckoo-modified#408]
I have like 50 processing job I don't need. I cannot find a good way to cancel/delete/purge all these jobs. when i try and do it through the API i get:

```
{
    "error_value": "Task is still being analyzed", 
    "error": true
}
```

is this something i'll need to drop into the mongo shell for? thanks for any tips!

**Comment by seanthegeek** [comment]
If you restart the Cuckoo process, it should switch all tasks that were still processing at the time to a failed status. After that they can be deleted using the HTTP API.

**Comment by housemusic42** [comment]
word. i just cranked up the parallel processing but i'll try that next time! thanks!

**Comment by misraramswaroop** [comment]
@seanthegeek I have restarted cuckoo and my status is "failed_analysis". But i am still facing same problem.   I was unable to delete through api.

"error_value" : "Task is still being analyzed".
