### ISSUE TITLE
sourcecode of CuckooMon for this sandbox

### ISSUE THREAD

**Issue by william-second** [spender-sandbox/cuckoo-modified#419]
Hi, 
Can I ask for the copy of sourcecode that has been used to compiled cuckoomon.dll of this sandbox? 
Thank you very much.

**Comment by doomedraven** [comment]
https://github.com/spender-sandbox/cuckoomon-modified

**Comment by william-second** [comment]
Hi, 
Maybe I did not express what I want clearly. As I understand, cuckoomon.dll (/analyzer/windows/dll/cuckoomon.dll) must be compiled from some sourcecode (similar to this https://github.com/cuckoosandbox/cuckoomon). Could you please let me know where I can download this? 
Thanks

**Comment by doomedraven** [comment]
check my link...

**Comment by william-second** [comment]
sorry.
