### ISSUE TITLE
tor.py and /usr/sbin/torstart | torstop

### ISSUE THREAD

**Issue by eoinmiller-sfdc** [spender-sandbox/cuckoo-modified#42]
Looking into the tor stuff and tor.py needs /usr/sbin/torstart and usr/sbin/torstop in order to operate but I can't find any reference to these kinds of files? Is there something missing?

**Comment by seanthegeek** [comment]
https://github.com/seanthegeek/routetor

**Comment by eoinmiller-sfdc** [comment]
Thanks @seanthegeek
