### ISSUE TITLE
Automatic package detection

### ISSUE THREAD

**Issue by Nwinternights** [spender-sandbox/cuckoo-modified#423]
Hi All,
I was trying to upload a bin file through web interface and i know that's a JS.
If i leave "auto" in  "analysis package" I get only static analysis of VT  with benign score but, if I force cuckoo to "js" i get all the behevour signature matched with 10 malscore.
Does anyone have any tips to workaround that issue?
the file is:
3e18dcfb2947a5252ddd238526e175f16b866c2b75da503c129e81fa8e587e07
thanks
M.

**Comment by spender-sandbox** [comment]
No way to work around it without adding some more code to packages.py to do deeper inspection of files with "ascii text" file type or whatever it was detected as.

-Brad

**Comment by Nwinternights** [comment]
thank you Brad for quick answer.
