### ISSUE TITLE
Domain and DNS Whitelist

### ISSUE THREAD

**Issue by big-gunter** [spender-sandbox/cuckoo-modified#433]
I think it's probably just fatigue. But for the life of me I can't get DNS or Domain whitelisting to work.

I've edited processing.conf to reflect the following:
dnswhitelist = 8.8.8.8,8.8.4.4

However they continue to be present in my reports.

I also wanted to whitelist some domains, for example:
teredo.ipv6.microsoft.com

I noted some conversations back about a domain.txt, but again for the life of me, can't work out how to make it work.

So I'm not sure if it's a bug or just me paying the price for burning the candle at both ends.

Help!

**Comment by spender-sandbox** [comment]
dnswhitelist is a on/off bool toggle, the actual domain whitelist is in:
https://github.com/spender-sandbox/cuckoo-modified/blob/master/modules/processing/network.py#L96

The IP whitelist is here:
https://github.com/spender-sandbox/cuckoo-modified/blob/master/modules/processing/network.py#L103
and gets filled in additionally by the results of resolving any whitelisted domains seen during analysis.

-Brad

**Comment by big-gunter** [comment]
Thanks Brad!

So I am correct in assuming if I've set the VM's DNS to 8.8.8.8, I need to add that to network.py, L103:
`self.ip_whitelist = set(8.8.8.8,8.8.4.4)`
I ask because this is the case and it still appears in my reports under the Network, Hosts page.

I'm also assuming I can edit entries under line 96 and add my own domains in the appropriate format?

Apologies, I'm sure this is annoying.

**Comment by spender-sandbox** [comment]
That'd cause invalid syntax.  Use:
self.ip_whitelist = set(["8.8.8.8","8.8.4.4"])

and make sure you restarted processing.  And yes, you can modify that other list.

-Brad

**Comment by spender-sandbox** [comment]
But also make sure that in your processing.conf you have "dnswhitelist = on" or none of this code will execute.

-Brad

**Comment by big-gunter** [comment]
Nailed it - worked like a charm! Thanks so much!
