### ISSUE TITLE
No procmemdump for some processes

### ISSUE THREAD

**Issue by jowayow** [spender-sandbox/cuckoo-modified#436]
Hi, I don't know I may be missing some basic concept but what are the possible reasons that some processes seen in the behavior tree don't have a corresponding procmemdump?

For example, the report of the sample c86f0608dae0da3d64773f92e970490b89760adb0bb1d819e5e5601d834b8ac4, these are the processes seen by volatility
![1](https://cloud.githubusercontent.com/assets/14179376/24701389/dcb57398-1a2c-11e7-9935-912f44216b5f.jpg)

But some of them does not have a procmemdump, for example **pid=2792**.
![2](https://cloud.githubusercontent.com/assets/14179376/24701417/f9ffb8be-1a2c-11e7-9830-afc02b532ed6.jpg)

Thanks!

**Comment by spender-sandbox** [comment]
With that many processes, and especially with something large like java and particularly if the processes are still running at the end of analysis, it'll be difficult to dump and transfer them all before the critical timeout is hit.  The analysis.log will show more info.

-Brad

**Comment by jowayow** [comment]
Oh okay I understand. Will do. Thanks.
