### ISSUE TITLE
api.py: "AttributeError: 'unicode' object has no attribute 'file'"

### ISSUE THREAD

**Issue by ghost** [spender-sandbox/cuckoo-modified#447]
Hi,

I use three servers for testing. One server is running api.py and dist.py, the other two servers are running api.py, cuckoo.py and process.py.

When submitting files directly to my servers running cuckoo.py via API /tasks/create/file , I receive no errors.
When my server which is running dist.py is submitting files to my servers running cuckoo.py, I receive the following error:

XXX - - [05/May/2017 14:17:52] "POST /tasks/create/file HTTP/1.1" 500 762
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/cuckoo-modified/utils/api.py", line 101, in tasks_create_file
    temp_file_path = store_temp_file(data.file.read(), data.filename)
AttributeError: 'unicode' object has no attribute 'file'

What I tried with no success so far: Upgrading cuckoo, upgrading relevant packages, small changes in api.py code. 

Does this error message appear for anyone with a similar setup too?
Could anyone give me some hints on how to debug this issue? I already started looking deeper into dist.py and api.py but I might search on the wrong spots. The above mentioned setup worked fine last month when I was testing.

Thank you very much for your input.

**Comment by doomedraven** [comment]
sound like not unicode name as far as i remember that is nto supported

**Comment by ghost** [comment]
thank you, removed the filename with unicode characters from my database. dist.py tried to submit the file to my sandbox nodes over and over again, that's why the error message came up. now it works fine

**Comment by doomedraven** [comment]
yup i know that, btw here is updates of dist.py
https://github.com/doomedraven/cuckoo-modified/blob/master/utils/dist.py
