### ISSUE TITLE
vSphere : Segfault while powering off virtual machine

### ISSUE THREAD

**Issue by Nagaev** [spender-sandbox/cuckoo-modified#457]
While running Cuckoo with the vsphere machinery, I get a segmentation fault while powering off the virtual machine. I don't have any error before this one.

```
$ python cuckoo.py --debug
(...)
[modules.machinery.vsphere] INFO: Powering off virtual machine W732
[lib.cuckoo.core.scheduler] DEBUG: Task #31: Released database task with status True
[lib.cuckoo.core.plugins] DEBUG: Executing processing module "Decompression" on analysis at "/opt/cuckoo/storage/analyses/31"
[lib.cuckoo.core.plugins] DEBUG: Executing processing module "AnalysisInfo" on analysis at "/opt/cuckoo/storage/analyses/31"
[lib.cuckoo.core.plugins] DEBUG: Executing processing module "BehaviorAnalysis" on analysis at "/opt/cuckoo/storage/analyses/31"
[lib.cuckoo.core.plugins] DEBUG: Executing processing module "Debug" on analysis at "/opt/cuckoo/storage/analyses/31"
[lib.cuckoo.core.plugins] DEBUG: Executing processing module "Dropped" on analysis at "/opt/cuckoo/storage/analysis/31"
Segmentation Fault
```

Do you know what is the problem?

**Comment by jgajek** [comment]
Looks like it's segfaulting when processing the Dropped files module, not while powering off the VM.

**Comment by doomedraven** [comment]
could be yara related i think you need to dig into core dump https://stackoverflow.com/a/34707522

**Comment by Nagaev** [comment]
Actually it seems the problem is related to some programs I have submitted. More precisely I wanted to test the stealth of my sandbox with tools like pafish or al-khaser (on W7 32bits). No segfault when submitting other programs/malwares (even when files are dropped). Can this segfault be caused by detection techniques used by these tools (which could be a problem regarding evasive malwares)?

**Comment by doomedraven** [comment]
no, bcz i have tested them and they work just fine. so you should dig into core dump as @jgajek told, it occurs on dropped files according to your log

**Comment by jgajek** [comment]
The segfault is occurring during analysis of the results, after the guest VM is already shut down.  You can try to disable the Dropped module in processing.conf and see if the segfault goes away.

**Comment by Nagaev** [comment]
Thank's for your answer. 

You're right, it is related to the Dropped module. It works when it is disabled. When executing al-khaser.exe analysis in valgrind, it says the segfault is indeed related to Yara ('General Protection Fault'). Do you know why since I didn't have any Yara rules at the moment. By the way do you know how to disable Yara? I disabled yarascan for memory analysis, but didn't find any modules related to Yara which I can disable.

**Comment by doomedraven** [comment]
which version of yara? i had that is why i told what it can be yara related, and is why i stay with v3.4, also yara should be compiled from source as bindings also, nothing from apt/pip

**Comment by Nagaev** [comment]
You're right, there were maybe something wrong with Yara, maybe I used apt-get or pip.

I have uninstalled yara and yara-python and reinstalled it from sources and eveything works!
https://github.com/VirusTotal/yara
https://github.com/VirusTotal/yara-python

Thank's!
