### ISSUE TITLE
traceback pool.py with some samples

### ISSUE THREAD

**Issue by Nwinternights** [spender-sandbox/cuckoo-modified#461]
Hi All,
does anybody has seen this error when submitting a particular sample?
Traceback (most recent call last):
  File "process.py", line 155, in autoprocess
    ar.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
KeyError: 'info'

**Comment by doomedraven** [comment]
normally happens when you disable info part in processing or reporting, not remember in which one, but apart of that if that is not your case no idea

**Comment by Nwinternights** [comment]
Solved...the problem was m2crypto that should have been upgraded!
I digged on logs and I found this error 
/../modules/processing/static.py", line 685, in _get_guest_digital_signers
    str(self.results["info"]["id"]), "aux",
KeyError: 'info'
