### ISSUE TITLE
Safe to update community plugins with afw?

### ISSUE THREAD

**Issue by DigiAngel** [spender-sandbox/cuckoo-modified#479]
Topic :)  Wasn't sure if this would pull down any cuckoo2 stuff.  Thank you.

**Comment by doomedraven** [comment]
the default way as always, `python community.py -waf`

**Comment by DigiAngel** [comment]
Ok cool thanks...is this something I should do on a regular basis?

**Comment by doomedraven** [comment]
now nop, repo is dead and Brad not accepting nothing, so you can manually merge them, but i wouldn't expect more signatures

**Comment by doomedraven** [comment]
read main readme

**Comment by DigiAngel** [comment]
Perfect..thanks so much!
