### ISSUE TITLE
Error when VM is trying to shut down.

### ISSUE THREAD

**Issue by kkburg** [spender-sandbox/cuckoo-modified#48]
Hello,

sometimes (not always, seems quite random to me) after an analysis when the VM tries to shut down, i'm getting the following errors.
[https://img5.picload.org/image/wlodgrc/cuckoo_error.jpg](url)
Then the VM does nothing and cuckoo gets stuck because its waiting on the VM.
Any ideas?

**Comment by spender-sandbox** [comment]
This is probably fixed by a recent series of commits.

-Brad
