### ISSUE TITLE
Feature Request: Re-run signatures

### ISSUE THREAD

**Issue by Fryyyyy** [spender-sandbox/cuckoo-modified#49]
When tuning signatures, it's kind of a pain to keep resubmitting the files.  Would it be possible to re-queue the analysis for processing, thus re-running the signatures but not having to do all the dynamic analysis again?

**Comment by spender-sandbox** [comment]
utils/process.py -r <task id> will do this

**Comment by Fryyyyy** [comment]
Oh, cool! Thanks :)
