### ISSUE TITLE
Analysis URL Missing IP/Host Part

### ISSUE THREAD

**Issue by hackdefendr** [spender-sandbox/cuckoo-modified#494]
I know that title isn't going to explain it very well...but when I launch an investigation and then click on the number (link to analysis) where I am greeted with a wait page that refreshes every 30 seconds...when the analysis is complete, the page refreshes to `https://analysis/21/` which is missing the IP/Host portion of the URL.

Anyone else seeing this?

Is it easily fixed?

**Comment by doomedraven** [comment]
check the processing module maybe there some logging which can give a clue what is wrong, and about the ip/host you mean in url or from the connections?

**Comment by hackdefendr** [comment]
Yes. I think. When waiting for the analysis to complete, whatever page that is.  It refreshes every 30 seconds, then when the analysis is complete it is supposed to forward to the analysis page, which is tries to do, but is missing the IP in the URL. So I get a "This Page Can't Be Reached" error page.

The URL looks like `https://analysis/21/` instead of `https://1.2.3.4/analysis/21/`

**Comment by doomedraven** [comment]
interesting, first time hearing about that

**Comment by hackdefendr** [comment]
So no idea about why this is happening or how to fix it?

**Comment by knicholson0** [comment]
I think I remember that issue happening on Malwr.  This was like 4-5 years ago.

**Comment by doomedraven** [comment]
reinstall cuckoo maybe

**Comment by hackdefendr** [comment]
I just did...that's why I'm asking.  

Seems that development here has stalled out.  So I guess I will just have to type the IP in every single time I run an Analysis. Hard to believe I am the only one seeing this issue.

**Comment by knicholson0** [comment]
Does the redirect also fail when you click the "click here" instead of waiting for analysis to finish and to be automatically redirected?

**Comment by hackdefendr** [comment]
Do you mean the little number link?  Yes when I click on that it shows me this:

![2018-04-20 12_50_42-cuckoo sandbox](https://user-images.githubusercontent.com/2224217/39066123-a37e6b1e-4499-11e8-909c-b70eb875a64d.png)

Then when the analysis is finished it tries to auto-redirect to the Analysis page, but instead drops the IP/URL of my Cuckoo Sandbox leaving:

`https://analysis/3/`

**Comment by hackdefendr** [comment]
No point leaving this issue open since no more development is happening on this repo.
