### ISSUE TITLE
run-detectors: unable to find an interpreter

### ISSUE THREAD

**Issue by azfarhalim** [spender-sandbox/cuckoo-modified#507]
Hi my issue is i cant submit the malware to analyze using command line

My cuckoo version 1.3-NG

when i run this command -
cuckoo@debian:~$ sudo /opt/cuckoo/utils/submit.py /home/cuckoo/Desktop/807d2dff72386e72bb07f9945a4fbd317eeb35e96357c143020e97a1e11434b4

this error is popped up
run-detectors: unable to find an interpreter for /opt/cuckoo/utils/submit.py

**Comment by doomedraven** [comment]
what about `python /opt/cuckoo/utils/submit.py /home/cuckoo/Desktop/807d2dff72386e72bb07f9945a4fbd317eeb35e96357c143020e97a1e11434b4`

**Comment by azfarhalim** [comment]
@doomedraven it throws this error

cuckoo@debian:~$ python /opt/cuckoo/utils/submit.py /home/cuckoo/Desktop/807d2dff72386e72bb07f9945a4fbd317eeb35e96357c143020e97a1e11434b4 
  File "/opt/cuckoo/utils/submit.py", line 1
SyntaxError: Non-ASCII character '\x90' in file /opt/cuckoo/utils/submit.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by doomedraven** [comment]
Add as first line
\# encoding: utf-8

**Comment by azfarhalim** [comment]
Thank you!
