### ISSUE TITLE
django 1.9 support? 

### ISSUE THREAD

**Issue by mallorybobalice** [spender-sandbox/cuckoo-modified#55]
Hi,

not sure if anyone inquired before.
Wondering whether anyone else tried installing and using the web interface + api with django 1.9?

I could be wrong, but this looks like it's enough to make it work for most things (just an import fix?) ? (or has someone tried it , looked  at the web server logs after and decided there's more issues with it). The change could be compatible with older versions too

web/analysis/views.py
``` 
< from wsgiref.util import FileWrapper
< #from django.core.servers.basehttp import FileWrapper
```

web/api/views.py
``` 
< from wsgiref.util import FileWrapper
< #from django.core.servers.basehttp import FileWrapper
```

thanks. 
mb

**Comment by KillerInstinct** [comment]
Could probably be done easily. The main holdup was that the django-ratelimit module didn't support 1.9. It looks like this has been resolved since I last looked.

https://github.com/jsocol/django-ratelimit/pull/96/files

**Comment by GeoffreyVDB** [comment]
ratelimit seems to be fixed but I think that it hasn't been pushed to the pip repository yet

**Comment by KillerInstinct** [comment]
Yes, if you git clone the repo and build it yourself, 1.9 should be supported, until the updated version makes it to pip.

**Comment by seanthegeek** [comment]
Confirmed. That works. Just sent in a PR to adjust `requirements.txt` so that anyone who runs `sudo pip install --upgrade -r requirements.txt`will get  that version.
