### ISSUE TITLE
Process.py seems to hang if encounters very large strings

### ISSUE THREAD

**Issue by pashashocky** [spender-sandbox/cuckoo-modified#58]
Some samples have strings of 11mb, the processing module seems to hang at:

'Processing strings'

pressing ctrl+c solves the issue and the report is regenerated, although then no strings show. 

Can we add a limit to the size of the string that we can process and add to mongo?

**Comment by spender-sandbox** [comment]
Do you have re2 installed?

**Comment by pashashocky** [comment]
I have just installed it, and it does seem to fix the problem when running with 
./process.py -r [task id] 

however it still doesn't complete at least quickly with 
./process -p 4 auto 

Ill test a bit more and get back to you. 

Thanks!

**Comment by pashashocky** [comment]
Seems to work! thanks :+1:
