### ISSUE TITLE
Checking if analysis already exists

### ISSUE THREAD

**Issue by dforce** [spender-sandbox/cuckoo-modified#6]
This is not an issue but more a question.

Is it possible to implement, when adding a file for analysis, that it first checks if there exists already an analysis for that file ?
If already exists, showing some kind of web page with some indication of the existing analysis and the possibility to view the analysis or submit that fie for a new analysis.

Thanks
Miguël

**Comment by jbertman** [comment]
I believe this logic is taken care of in the scheduler. You could return from there. Also, you may want to look at the resubmitexe logic, as that may be related to what you are trying to do.
cuckoo-modified/lib/cuckoo/core/scheduler.py - line 123
```
if os.path.exists(self.binary):
            log.info("File already exists at \"%s\"", self.binary)
            # Could we return here?
        else:
            # TODO: do we really need to abort the analysis in case we are not
            # able to store a copy of the file?
            try:
                shutil.copy(self.task.target, self.binary)
            except (IOError, shutil.Error) as e:
                log.error("Unable to store file from \"%s\" to \"%s\", "
                          "analysis aborted", self.task.target, self.binary)
                return False
```

**Comment by mallorybobalice** [comment]
There is room for improvement in checking demuxed files submitted via submit.py utility. 

 I.e archives. also, i don't think the web interface has the unique option or maybe that's passable as a param?

For checking demuxed files, someone can try to merge the following changes or a variation on this

vi utils/submit.py.
find the db.demux_sample_and_add_to_db

and for the wrapping else statement:

             else:
		aNumTasks=None
                if args.unique:
                    aNumTasks=[-1,-1]
                    sha256 = File(file_path).get_sha256()
                    if not db.find_sample(sha256=sha256) is None:
                        msg = ": Sample {0} (skipping file)".format(file_path)
                        if not args.quiet:
                            print(bold(yellow("Duplicate")) + msg)
                        continue
                task_ids = db.demux_sample_and_add_to_db(file_path=file_path, package=args.package, timeout=sane_timeout, options=args.options,
                                                         priority=args.priority, machine=args.machine, platform=args.platform, memory=args.memory,
                                                         custom=args.custom, enforce_timeout=args.enforce_timeout, clock=args.clock, tags=args.tags, unique=args.unique,numTasks=aNumTasks)

            tasks_count = len(task_ids)
            if tasks_count > 1:
                if not args.quiet:
                    print(bold(green("Success")) + u": File \"{0}\" added as task with IDs {1}".format(file_path, task_ids))
            elif tasks_count > 0:
                if not args.quiet:
                    print(bold(green("Success")) + u": File \"{0}\" added as task with ID {1}".format(file_path, task_ids[0]))
            else:
                if args.unique and aNumTasks is not None:
                        print(bold(green("Success")) + u": File \"{0}\" had no unique tasks after demuxing: {1} of {2}".format(file_path,aNumTasks[0],aNumTasks[1]))
                else:
                        print(bold(red("Error")) + ": adding task to database")





vi lib/cuckoo/core/database.py
find  def demux_sample_and_add_to_db and replace it with the below. 



 def demux_sample_and_add_to_db(self, file_path, timeout=0, package="", options="", priority=1,
                                   custom="", machine="", platform="", tags=None,
                                   memory=False, enforce_timeout=False, clock=None,shrike_url=None,
                                   shrike_msg=None, shrike_sid = None, shrike_refer=None, parent_id=None, unique=False,numTasks=None):
        """
        Handles ZIP file submissions, submitting each extracted file to the database
        Returns a list of added task IDs
        """
        task_ids = []
        # extract files from the (potential) ZIP
        extracted_files = demux_sample(file_path, package, options)
        # create tasks for each file in the ZIP
        numAdded=len(extracted_files)
        if unique and numTasks is not None:
                numTasks[1]=numAdded
        for file in extracted_files:
            if unique:
                sha256 = File(file).get_sha256()
                log.debug( 'unique?check extracted sha256 %s path %s', sha256, file)
                if not self.find_sample(sha256=sha256) is None:
                        msg = ": Sample {0} (skipping file)".format(file)
                        log.debug('Duplicate %s', msg)
                        numAdded -= 1
                        continue
                else:
                        log.debug('sample not found in db and is not a duplicate %s', file)
            task_id = self.add_path(file_path=file,
                                    timeout=timeout,
                                    priority=priority,
                                    options=options,
                                    package=package,
                                    machine=machine,
                                    platform=platform,
                                    memory=memory,
                                    custom=custom,
                                    enforce_timeout=enforce_timeout,
                                    tags=tags,
                                    clock=clock,
                                    shrike_url=shrike_url,
                                    shrike_msg=shrike_msg,
                                    shrike_sid=shrike_sid,
				    shrike_refer=shrike_refer,
                                    parent_id=parent_id)

            if task_id:
                task_ids.append(task_id)

        if numTasks is not None:
                numTasks[0]=numAdded

        return task_ids

**Comment by afont** [comment]
You can use the API, once you have the file checksum calculated:

For example with md5 digest:
$ curl -s http://<cuckoo>/api/files/view/md5/${md5Digest}/

Then parse the output. The same applies for URL's.
