### ISSUE TITLE
AWS Support

### ISSUE THREAD

**Issue by sooshie** [spender-sandbox/cuckoo-modified#60]
Any interest in a PR that adds AWS support to the UI/datastore.

The UI has hooks to grab information from S3 buckets, and there is an output AWS plugin that moves stuff from the local FS to S3. I've run over 12k samples through it and it seems to be working fine. I didn't patch the API for retrieval since getting data from S3 is pretty trivial. The only downside to the patch is you lose search functionality. Open to suggestions/thoughts.

**Comment by spender-sandbox** [comment]
Yes, gimme!

**Comment by sooshie** [comment]
Ok, let me true it up with the latest stuff you've got out here (I think I'm a few pulls behind). I should be able to get it to you this week tho.

**Comment by spender-sandbox** [comment]
Sounds good -- I guess it's implemented as a reporting module?

**Comment by sooshie** [comment]
Correct, reporting module for sending data, and then added code to views.py to retrieve it for the UI.
