### ISSUE TITLE
Feature request: tag analysis optimization

### ISSUE THREAD

**Issue by pashashocky** [spender-sandbox/cuckoo-modified#62]
The idea here is for a user to be able to insert a certain tag, say 'network' and processing would only analyze the network for that sample. Is this possible to do already, or i could implement it and submit a pull request?

Would this have a significant effect on performance on large batches? What would be another way of optimizing this or similar behaviour?

**Comment by spender-sandbox** [comment]
You could always run an analysis without injection -- that would leave pretty much only network processing.

-Brad

**Comment by pashashocky** [comment]
Yeah, looked through the code, and did some tests, seems like it :)
