### ISSUE TITLE
recent database.py changes look to make cuckoo indefinitely wait in waiting for analysis tasks?

### ISSUE THREAD

**Issue by mallorybobalice** [spender-sandbox/cuckoo-modified#64]
Hi, 

not sure what I'm doing wrong, but after I've cloned the latest master (including https://github.com/spender-sandbox/cuckoo-modified/commit/464f9be8ce1141b8a15ae82a19e1898c15ec913e)  
cuckoo main (as in cuckoo.py ) starts, loads modules, machinery etc. 

Then indefinitely stays in 

2016-03-01 20:36:18,036 [lib.cuckoo.common.abstracts] DEBUG: Getting status for puppies1
2016-03-01 20:36:18,108 [lib.cuckoo.common.abstracts] DEBUG: Getting status for puppies2
2016-03-01 20:36:18,135 [lib.cuckoo.core.scheduler] INFO: Loaded 2 machine/s
2016-03-01 20:36:18,144 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
...
nothing after.

newly submitted or already queued tasks don't seem to get picked up by cuckoo main, but  Web UI displays the new tasks in the queue fine. 

looking at  https://github.com/spender-sandbox/cuckoo-modified/blob/master/lib/cuckoo/core/database.py

Possibly the today's session close commits or maybe the session.query  one? 
reverting today's database.py commits makes it work ok. 

Running mysql + mongo for the DBs.

**Comment by spender-sandbox** [comment]
Will fix that today -- the previous bug made the non-specified VM case work by accident, so fixing it seems to have left that case broken (we'd simply go through the available VM list and find no task set to run on it specifically, and those will all remain in pending state).

-Brad

**Comment by spender-sandbox** [comment]
Fixed with latest commit.

-Brad
