### ISSUE TITLE
Sample of ISRStealer fails to communicate

### ISSUE THREAD

**Issue by seanthegeek** [spender-sandbox/cuckoo-modified#70]
I recently came across a sample of ISRStealer ( `1a5a0d2ae44eb5d19fa83dfbea710e3890eabc39700d2271dcd6807d444d024e` on VirusTotal). It communicates when run in a commercial sandbox, but it doesn't create any network traffic in my instance of Cuckoo. Any ideas?

**Comment by spender-sandbox** [comment]
This is most likely a problem with your .NET installation in the VM.  You probably see the main executable exiting somewhat early with a 0x80131700 error code.  I was able to run it fine in a Win 7 VM with all .NET versions installed.

**Comment by seanthegeek** [comment]
SIt takes a bit to exit, and exits normally. I have .NET 4.5 installed. I'll try 5.6.1.
