### ISSUE TITLE
MultiCore Processing

### ISSUE THREAD

**Issue by eoinmiller-sfdc** [spender-sandbox/cuckoo-modified#71]
So I tried switching off processing as per:
https://github.com/spender-sandbox/cuckoo-modified/blob/daec595861696c3d0e73d0bee0c6e22af9603f26/docs/book/src/usage/performance.rst

"Multi-Core processing

By switching off processing ( conf/cuckoo.conf, process_results in [cuckoo]) the processing step can be done in a separate utils/process.py task running several process."

However the results never seem to get processed and each task is just listed as "processing" in the web-ui. Is there some other step I am missing here?

**Comment by spender-sandbox** [comment]
Yes, you have to run 'utils/process.py -p <num threads> auto' yourself.

-Brad
