### ISSUE TITLE
PassiveTotal Links On Suricata Alerts Page

### ISSUE THREAD

**Issue by eoinmiller-sfdc** [spender-sandbox/cuckoo-modified#75]
Happened to notice when turning on Suricata integration, the links to [VT] for source IP,dest IP, and host appear, however the links for PassiveTotal [PT] appear to be absent even when it is enabled in auxiliary.conf.

![image](https://cloud.githubusercontent.com/assets/15840028/13822076/b564e198-eb7a-11e5-81d4-6eeded643ade.png)

**Comment by Soukaiinaa** [comment]
@eoinmiller-sfdc Can you tell me please, how you did to integrate suricata with cuckoo sandbox ?

**Comment by doomedraven** [comment]
Google it, there tons of answers, install suricata and configure it in config of cuckoo, done
