### ISSUE TITLE
Analysis crashed cuckoomon

### ISSUE THREAD

**Issue by lpaine** [spender-sandbox/cuckoo-modified#77]
Got a signature popping on a piece of malware with the message "Crashed cuckoomon during analysis. Report this issue to the github repo"

pid: 2388
message: Exception reported at offset 0xf241 in cuckoomon itself

**Comment by spender-sandbox** [comment]
Is this with the latest version?  If not, can you repeat it with the latest version so I can look at the proper offset?

Thanks,
-Brad

**Comment by lpaine** [comment]
Hey, updated to the latest and greatest from 4hrs ago. Here is your new offset:

pid: 2396
message: Exception reported at offset 0xfd21 in cuckoomon itself

**Comment by spender-sandbox** [comment]
Thanks, should be fixed now.

-Brad

**Comment by lpaine** [comment]
Just ran my sample with no errors. I appreciate the prompt fix!
