### ISSUE TITLE
No folders made on host

### ISSUE THREAD

**Issue by dforce** [spender-sandbox/cuckoo-modified#81]
Running the latest commit, the one from a few hours ago, and noticed that there is no creation of folder on the host when running analysis.
Just a copy of the binary and the dump.pcap is created.
Pinging between host and guest is no problem.

Can this be solved ?

Thanks

**Comment by spender-sandbox** [comment]
Should be fixed now, was missing some changes somehow.

-Brad

**Comment by dforce** [comment]
Problem solved.

Thanks
