### ISSUE TITLE
Multiple VM virtualbox

### ISSUE THREAD

**Issue by Sirskinny** [spender-sandbox/cuckoo-modified#87]
When adding these lines to my virtual box conf:

> Specify a comma-separated list of available machines to be used. For each
>  specified ID you have to define a dedicated section containing the details
>  on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
> machines = cuckoo1,cuckoo2
> 
> [cuckoo1]
>  Specify the label name of the current machine as specified in your
> VirtualBox configuration.
> label = cuckoo1
> 
> [cuckoo2]
>  Specify the label name of the current machine as specified in your
>  VirtualBox configuration.
> label = cuckoo2

I get this error when starting cuckoo:

> Traceback (most recent call last):
>   File "cuckoo.py", line 132, in <module>
>     cuckoo_main(max_analysis_count=args.max_analysis_count)
>   File "cuckoo.py", line 78, in cuckoo_main
>     sched.start()
>   File "/home/malware/Documents/2/cuckoo-modified-master/lib/cuckoo/core/scheduler.py", line 549, in start
>     self.initialize()
>   File "/home/malware/Documents/2/cuckoo-modified-master/lib/cuckoo/core/scheduler.py", line 517, in initialize
>     machinery.initialize(machinery_name)
>   File "/home/malware/Documents/2/cuckoo-modified-master/lib/cuckoo/common/abstracts.py", line 94, in initialize
>     self._initialize(module_name)
>   File "/home/malware/Documents/2/cuckoo-modified-master/lib/cuckoo/common/abstracts.py", line 112, in _initialize
>     machine.platform = machine_opts["platform"]
> KeyError: 'platform'

I was hoping someone would be able to help me out. Thanks for everything!

-Alex

**Comment by spender-sandbox** [comment]
There are other required fields for each VM you define.  In your case you seem to have commented out or removed the "platform" field.

-Brad

**Comment by Sirskinny** [comment]
Brad,

Thank you for the quick response! Sorry for posting on this forum!

Thanks
-Alex
