### ISSUE TITLE
IOError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by mohammadrad** [spender-sandbox/cuckoo-modified#90]
1:33] 
File /cuckoo-modified/lib/cuckoo/core/resultserver.py", line 367, in read_next_message
   infofd = open(file_path + "_info.txt", "a")
IOError: [Errno 36] File name too long: /cuckoo-modified/storage/analyses/272/files/987896037/\\xc3\\x81\\xc3\\xa0\\xc3\\xa7\\xc3\\xa0 email.txt eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.exe_info.txt'

Instead of storing the full url as the filename, can we hash it?

**Comment by spender-sandbox** [comment]
Should be fixed now, thanks for the report!

-Brad
