### ISSUE TITLE
VirusTotal Download via API?

### ISSUE THREAD

**Issue by eoinmiller-sfdc** [spender-sandbox/cuckoo-modified#94]
Is there an API call that can be made to Cuckoo that would pull down and detonate a sample from VirusTotal? In looking through the API I can't seem to find it.

**Comment by doomedraven** [comment]
in submit page you have it if you enable in conf and specify apikey

**Comment by eoinmiller-sfdc** [comment]
I'm aware of being able to do this through the web interface, but I would rather just make an API call with the hash for automation purposes.

**Comment by doomedraven** [comment]
@eoinmiller-sfdc just read this part of code :) https://github.com/spender-sandbox/cuckoo-modified/blob/master/web/api/views.py#L500

**Comment by doomedraven** [comment]
`url(r"^tasks/create/vtdl/$", "api.views.tasks_vtdl"), ` enjoy :)

**Comment by doomedraven** [comment]
i hope it will be added to webgui :)
https://github.com/spender-sandbox/cuckoo-modified/pull/133

**Comment by doomedraven** [comment]
@eoinmiller-sfdc update cuckoo you now have have help in /api/ :)
 `curl -F vtdl=hash_here http:cuckoo_box/tasks/create/vtdl`
