### ISSUE TITLE
Cuckoomon crash

### ISSUE THREAD

**Issue by lpaine** [spender-sandbox/cuckoo-modified#95]
Part two of an analysis crashing cuckoomon:

This is with latest as of 20m ago:

pid: 1184
message: Exception reported at offset 0xdf10 in cuckoomon itself

**Comment by spender-sandbox** [comment]
What's the md5sum of your cuckoomon.dll ?  While that offset matches up with an instruction, it's not one that can cause an exception.

-Brad

**Comment by lpaine** [comment]
Cuckoomon.dll: 729dd741f2a1c206dfa35267bc1017d2
Cuckoomon_x64.dll: 1aa084542387bda032f514f42a3e81f5

**Comment by spender-sandbox** [comment]
Odd, I would need to see the sample then to see what's going on.

-Brad

**Comment by lpaine** [comment]
I can definitely get you a copy of the sample if you'd like

**Comment by spender-sandbox** [comment]
That'd work, or just the hash if it's on VT.

-Brad

**Comment by lpaine** [comment]
It sure is:

SHA1: a357aa6b61d126ff596d2d5d9b1150a90793a5b6

https://www.virustotal.com/en/file/9d37a56442a398ce827a4a2f4718c49bff7ff90a4a1fb29f7c4d81d7ab90d4bb/analysis/

**Comment by spender-sandbox** [comment]
Ok, I see the problem -- will fix it shortly.

-Brad

**Comment by spender-sandbox** [comment]
Should be fixed now, thanks for the report!

-Brad

**Comment by lpaine** [comment]
Sure is, just verified! Thanks!
