### ISSUE TITLE
.tgz files -> Error: Analysis failed: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.

### ISSUE THREAD

**Issue by afont** [spender-sandbox/cuckoo-modified#96]
I face this error when submitting a '.tgz' file.
With zip, rar, tar, tar.gz files work fine, but not with .tgz files.

Any way to fix it?

Thanks

**Comment by spender-sandbox** [comment]
I was just working on this actually, should have support for it and a bunch of other stuff very soon.

-Brad

**Comment by spender-sandbox** [comment]
There, should be fixed now.

-Brad

**Comment by afont** [comment]
Thanks Brad!

Alex
